###############################################################
#  Generated by:      Cadence Innovus 20.15-s105_1
#  OS:                Linux x86_64(Host ID ee21)
#  Generated on:      Mon Jul 31 20:58:48 2023
#  Design:            CHIP
#  Command:           saveIoFile -byOrder CHIP.io
###############################################################

###############################################################
#  You can modify by your own
#  You can modify by your own
#  You can modify by your own
###############################################################

# Syntax: 
#(inst  name="PAD_NAME"	  place_status=placed )
#(endspace gap=50)

(globals
    version = 3
	space = 31
    io_order = default
)

(iopad
    (top		
        (inst  name="VDDP0" 	          place_status=placed)
        (inst  name="VDDC0" 	          place_status=placed)
        (inst  name="I_DATA0" 	          place_status=placed)
        (inst  name="I_DATA1" 	          place_status=placed)
        (inst  name="I_DATA2" 	          place_status=placed)
        (inst  name="I_DATA3" 	          place_status=placed)
        (inst  name="I_DATA4" 	          place_status=placed)
        (inst  name="I_DATA5" 	          place_status=placed)
        (inst  name="I_DATA6" 	          place_status=placed)
        (inst  name="I_DATA7" 	          place_status=placed)
        (inst  name="GNDC0" 	          place_status=placed)
        (inst  name="GNDP0" 	          place_status=placed)

        (endspace gap=50)
    )
    (right

        (inst  name="VDDP1" 	          place_status=placed)
        (inst  name="VDDC1" 	          place_status=placed)
        (inst  name="I_CMD0" 	          place_status=placed)
        (inst  name="I_CMD1" 	          place_status=placed)
        (inst  name="I_CMD2" 	          place_status=placed)
        (inst  name="I_CMD3" 	          place_status=placed)
        (inst  name="I_CMD4" 	          place_status=placed)
        (inst  name="I_CMD5" 	          place_status=placed)
        (inst  name="I_CMD6" 	          place_status=placed)
        (inst  name="I_CMD7" 	          place_status=placed)
        (inst  name="GNDC1" 	          place_status=placed)
        (inst  name="GNDP1" 	          place_status=placed)

        (endspace gap=50)

    )
    (bottom
		(inst  name="VDDP2" 	          place_status=placed)
        (inst  name="VDDC2" 	          place_status=placed)
        (inst  name="I_CMD8" 	          place_status=placed)
        (inst  name="I_CMD9" 	          place_status=placed)
        (inst  name="I_CMD10" 	          place_status=placed)
        (inst  name="I_CMD11" 	          place_status=placed)
        (inst  name="I_RST" 	          place_status=placed)
        (inst  name="I_CMD12" 	          place_status=placed)
        (inst  name="I_CMD13" 	          place_status=placed)
        (inst  name="I_CMD14" 	          place_status=placed)
        (inst  name="I_CMD15" 	          place_status=placed)
        (inst  name="GNDC2" 	          place_status=placed)
        (inst  name="GNDP2" 	          place_status=placed)
        
        (endspace gap=50)
    )
    (left
		(inst  name="VDDP3" 	          place_status=placed)
        (inst  name="VDDC3" 	          place_status=placed)
        (inst  name="I_CMD16" 	          place_status=placed)
        (inst  name="I_CMD17" 	          place_status=placed)
        (inst  name="I_CLK" 	          place_status=placed)
        (inst  name="I_IN_VALID_CMD" 	  place_status=placed)
        (inst  name="I_IN_VALID_DATA"     place_status=placed)
        (inst  name="O_BUSY" 	          place_status=placed)
        (inst  name="GNDC3" 	          place_status=placed)
        (inst  name="GNDP3" 	          place_status=placed)

        (endspace gap=50)
    )
	(topright
        (inst  name="topright"        cell="CORNERD" )
    )
    (topleft
        (inst  name="topleft"         cell="CORNERD" )
    )
    (bottomright
        (inst  name="bottomright"     cell="CORNERD" )
    )
    (bottomleft
        (inst  name="bottomleft"      cell="CORNERD" )
    )
)

