 
****************************************
Report : resources
Design : GTE
Version: T-2022.03
Date   : Sat Nov 29 19:44:23 2025
****************************************


Resource Report for this hierarchy in file ../01_RTL/GTE.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| add_x_1        | DW01_inc       | width=16   | add_105 (GTE.v:105)        |
| add_x_3        | DW01_inc       | width=9    | add_125 (GTE.v:125)        |
| add_x_5        | DW01_inc       | width=9    | add_134 (GTE.v:134)        |
| lte_x_24       | DW_cmp         | width=7    | lte_937 (GTE.v:937)        |
| gt_x_28        | DW_cmp         | width=7    | gt_950 (GTE.v:950)         |
| lte_x_29       | DW_cmp         | width=7    | lte_950 (GTE.v:950)        |
| gt_x_31        | DW_cmp         | width=7    | gt_963 (GTE.v:963)         |
| lte_x_32       | DW_cmp         | width=7    | lte_963 (GTE.v:963)        |
| gt_x_34        | DW_cmp         | width=7    | gt_976 (GTE.v:976)         |
| lte_x_35       | DW_cmp         | width=7    | lte_976 (GTE.v:976)        |
| lte_x_38       | DW_cmp         | width=7    | lte_989 (GTE.v:989)        |
| gt_x_42        | DW_cmp         | width=7    | gt_1002 (GTE.v:1002)       |
| lte_x_43       | DW_cmp         | width=7    | lte_1002 (GTE.v:1002)      |
| gt_x_45        | DW_cmp         | width=7    | gt_1015 (GTE.v:1015)       |
| lte_x_46       | DW_cmp         | width=7    | lte_1015 (GTE.v:1015)      |
| gt_x_50        | DW_cmp         | width=7    | gt_1028 (GTE.v:1028)       |
| lt_x_78        | DW_cmp         | width=7    | lt_143 (GTE.v:143)         |
|                |                |            | lt_191_6 (GTE.v:191)       |
|                |                |            | lt_205_6 (GTE.v:205)       |
|                |                |            | lt_219_6 (GTE.v:219)       |
|                |                |            | lt_233_6 (GTE.v:233)       |
|                |                |            | lt_297 (GTE.v:297)         |
| gte_x_79       | DW_cmp         | width=7    | gte_144 (GTE.v:144)        |
|                |                |            | gte_298 (GTE.v:298)        |
| lt_x_80        | DW_cmp         | width=7    | lt_148 (GTE.v:148)         |
|                |                |            | lt_251_2 (GTE.v:251)       |
|                |                |            | lt_260_2 (GTE.v:260)       |
|                |                |            | lt_367_2 (GTE.v:367)       |
| gte_x_81       | DW_cmp         | width=7    | gte_149 (GTE.v:149)        |
|                |                |            | gte_269 (GTE.v:269)        |
|                |                |            | gte_282 (GTE.v:282)        |
| lt_x_82        | DW_cmp         | width=7    | lt_191_3 (GTE.v:191)       |
|                |                |            | lt_205_3 (GTE.v:205)       |
|                |                |            | lt_219_3 (GTE.v:219)       |
|                |                |            | lt_233_3 (GTE.v:233)       |
| lt_x_83        | DW_cmp         | width=7    | lt_191_5 (GTE.v:191)       |
|                |                |            | lt_205_5 (GTE.v:205)       |
|                |                |            | lt_219_5 (GTE.v:219)       |
|                |                |            | lt_233_5 (GTE.v:233)       |
| lt_x_84        | DW_cmp         | width=7    | lt_191_7 (GTE.v:191)       |
|                |                |            | lt_205_7 (GTE.v:205)       |
|                |                |            | lt_219_7 (GTE.v:219)       |
|                |                |            | lt_233_7 (GTE.v:233)       |
| lte_x_85       | DW_cmp         | width=7    | lte_1084 (GTE.v:1084)      |
|                |                |            | lte_939 (GTE.v:939)        |
| gt_x_86        | DW_cmp         | width=7    | gt_1094 (GTE.v:1094)       |
|                |                |            | gt_952 (GTE.v:952)         |
| gt_x_87        | DW_cmp         | width=9    | gt_1004_2 (GTE.v:1004)     |
|                |                |            | gt_1017_2 (GTE.v:1017)     |
|                |                |            | gt_1030_2 (GTE.v:1030)     |
|                |                |            | gt_1084 (GTE.v:1084)       |
|                |                |            | gt_1094_2 (GTE.v:1094)     |
|                |                |            | gt_1103_2 (GTE.v:1103)     |
|                |                |            | gt_1112_2 (GTE.v:1112)     |
|                |                |            | gt_1121_2 (GTE.v:1121)     |
|                |                |            | gt_1130_2 (GTE.v:1130)     |
|                |                |            | gt_1139_2 (GTE.v:1139)     |
|                |                |            | gt_1148_2 (GTE.v:1148)     |
|                |                |            | gt_939 (GTE.v:939)         |
|                |                |            | gt_952_2 (GTE.v:952)       |
|                |                |            | gt_965_2 (GTE.v:965)       |
|                |                |            | gt_978_2 (GTE.v:978)       |
|                |                |            | gt_991_2 (GTE.v:991)       |
| lte_x_88       | DW_cmp         | width=7    | lte_1094 (GTE.v:1094)      |
|                |                |            | lte_952 (GTE.v:952)        |
| gt_x_89        | DW_cmp         | width=7    | gt_1103 (GTE.v:1103)       |
|                |                |            | gt_965 (GTE.v:965)         |
| lt_x_90        | DW_cmp         | width=16   | lt_1105 (GTE.v:1105)       |
|                |                |            | lt_960 (GTE.v:960)         |
| gte_x_91       | DW_cmp         | width=16   | gte_1114 (GTE.v:1114)      |
|                |                |            | gte_973 (GTE.v:973)        |
| lte_x_92       | DW_cmp         | width=7    | lte_1103 (GTE.v:1103)      |
|                |                |            | lte_965 (GTE.v:965)        |
| gt_x_93        | DW_cmp         | width=7    | gt_1112 (GTE.v:1112)       |
|                |                |            | gt_978 (GTE.v:978)         |
| lte_x_94       | DW_cmp         | width=7    | lte_1112 (GTE.v:1112)      |
|                |                |            | lte_978 (GTE.v:978)        |
| lt_x_96        | DW_cmp         | width=16   | lt_1123 (GTE.v:1123)       |
|                |                |            | lt_986 (GTE.v:986)         |
| gte_x_97       | DW_cmp         | width=16   | gte_1132 (GTE.v:1132)      |
|                |                |            | gte_999 (GTE.v:999)        |
| lte_x_98       | DW_cmp         | width=7    | lte_1121 (GTE.v:1121)      |
|                |                |            | lte_991 (GTE.v:991)        |
| gt_x_99        | DW_cmp         | width=7    | gt_1004 (GTE.v:1004)       |
|                |                |            | gt_1130 (GTE.v:1130)       |
| lt_x_100       | DW_cmp         | width=16   | lt_1132 (GTE.v:1132)       |
|                |                |            | lt_999 (GTE.v:999)         |
| gte_x_101      | DW_cmp         | width=16   | gte_1012 (GTE.v:1012)      |
|                |                |            | gte_1141 (GTE.v:1141)      |
| lte_x_102      | DW_cmp         | width=7    | lte_1004 (GTE.v:1004)      |
|                |                |            | lte_1130 (GTE.v:1130)      |
| gt_x_103       | DW_cmp         | width=7    | gt_1017 (GTE.v:1017)       |
|                |                |            | gt_1139 (GTE.v:1139)       |
| lt_x_104       | DW_cmp         | width=16   | lt_1012 (GTE.v:1012)       |
|                |                |            | lt_1141 (GTE.v:1141)       |
| gte_x_105      | DW_cmp         | width=16   | gte_1025 (GTE.v:1025)      |
|                |                |            | gte_1150 (GTE.v:1150)      |
| lte_x_106      | DW_cmp         | width=7    | lte_1017 (GTE.v:1017)      |
|                |                |            | lte_1139 (GTE.v:1139)      |
| gt_x_107       | DW_cmp         | width=7    | gt_1030 (GTE.v:1030)       |
|                |                |            | gt_1148 (GTE.v:1148)       |
| add_x_25       | DW01_add       | width=12   | add_938 (GTE.v:938)        |
|                |                |            | add_951 (GTE.v:951)        |
|                |                |            | add_964 (GTE.v:964)        |
|                |                |            | add_977 (GTE.v:977)        |
| add_x_26       | DW01_add       | width=12   | add_940 (GTE.v:940)        |
|                |                |            | add_953 (GTE.v:953)        |
|                |                |            | add_966 (GTE.v:966)        |
|                |                |            | add_979 (GTE.v:979)        |
| add_x_39       | DW01_add       | width=11   | add_1003 (GTE.v:1003)      |
|                |                |            | add_990 (GTE.v:990)        |
| add_x_40       | DW01_add       | width=11   | add_1005 (GTE.v:1005)      |
|                |                |            | add_992 (GTE.v:992)        |
| add_x_47       | DW01_add       | width=10   | add_1016 (GTE.v:1016)      |
|                |                |            | add_1029 (GTE.v:1029)      |
| add_x_48       | DW01_add       | width=10   | add_1018 (GTE.v:1018)      |
|                |                |            | add_1031 (GTE.v:1031)      |
=============================================================================


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| add_x_1            | DW01_inc         | apparch (area)     |                |
| add_x_3            | DW01_inc         | apparch (area)     |                |
| add_x_5            | DW01_inc         | apparch (area)     |                |
| lte_x_24           | DW_cmp           | apparch (area)     |                |
| gt_x_28            | DW_cmp           | apparch (area)     |                |
| lte_x_29           | DW_cmp           | apparch (area)     |                |
| gt_x_31            | DW_cmp           | apparch (area)     |                |
| lte_x_32           | DW_cmp           | apparch (area)     |                |
| gt_x_34            | DW_cmp           | apparch (area)     |                |
| lte_x_35           | DW_cmp           | apparch (area)     |                |
| lte_x_38           | DW_cmp           | apparch (area)     |                |
| gt_x_42            | DW_cmp           | apparch (area)     |                |
| lte_x_43           | DW_cmp           | apparch (area)     |                |
| gt_x_45            | DW_cmp           | apparch (area)     |                |
| lte_x_46           | DW_cmp           | apparch (area)     |                |
| gt_x_50            | DW_cmp           | apparch (area)     |                |
| lt_x_78            | DW_cmp           | apparch (area)     |                |
| gte_x_79           | DW_cmp           | apparch (area)     |                |
| lt_x_80            | DW_cmp           | apparch (area)     |                |
| gte_x_81           | DW_cmp           | apparch (area)     |                |
| lt_x_82            | DW_cmp           | apparch (area)     |                |
| lt_x_83            | DW_cmp           | apparch (area)     |                |
| lt_x_84            | DW_cmp           | apparch (area)     |                |
| lte_x_85           | DW_cmp           | apparch (area)     |                |
| gt_x_86            | DW_cmp           | apparch (area)     |                |
| gt_x_87            | DW_cmp           | apparch (area)     |                |
| lte_x_88           | DW_cmp           | apparch (area)     |                |
| gt_x_89            | DW_cmp           | apparch (area)     |                |
| lt_x_90            | DW_cmp           | apparch (area)     |                |
| gte_x_91           | DW_cmp           | apparch (area)     |                |
| lte_x_92           | DW_cmp           | apparch (area)     |                |
| gt_x_93            | DW_cmp           | apparch (area)     |                |
| lte_x_94           | DW_cmp           | apparch (area)     |                |
| lt_x_96            | DW_cmp           | apparch (area)     |                |
| gte_x_97           | DW_cmp           | apparch (area)     |                |
| lte_x_98           | DW_cmp           | apparch (area)     |                |
| gt_x_99            | DW_cmp           | apparch (area)     |                |
| lt_x_100           | DW_cmp           | apparch (area)     |                |
| gte_x_101          | DW_cmp           | apparch (area)     |                |
| lte_x_102          | DW_cmp           | apparch (area)     |                |
| gt_x_103           | DW_cmp           | apparch (area)     |                |
| lt_x_104           | DW_cmp           | apparch (area)     |                |
| gte_x_105          | DW_cmp           | apparch (area)     |                |
| lte_x_106          | DW_cmp           | apparch (area)     |                |
| gt_x_107           | DW_cmp           | apparch (area)     |                |
| add_x_25           | DW01_add         | apparch (area)     |                |
| add_x_26           | DW01_add         | apparch (area)     |                |
| add_x_39           | DW01_add         | apparch (area)     |                |
| add_x_40           | DW01_add         | apparch (area)     |                |
| add_x_47           | DW01_add         | apparch (area)     |                |
| add_x_48           | DW01_add         | apparch (area)     |                |
===============================================================================

1
