 
****************************************
Report : resources
Design : CONVEX
Version: T-2022.03
Date   : Mon Sep 29 11:58:26 2025
****************************************


Resource Report for this hierarchy in file ../01_RTL/CONVEX.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| sub_x_1        | DW01_dec       | width=9    | sub_97 (CONVEX.v:97)       |
| lte_x_2        | DW_cmp         | width=32   | lte_97 (CONVEX.v:97)       |
| lt_x_3         | DW_cmp         | width=8    | lt_98 (CONVEX.v:98)        |
| gte_x_4        | DW_cmp         | width=8    | gte_99_2 (CONVEX.v:99)     |
| add_x_18       | DW01_inc       | width=8    | add_205 (CONVEX.v:205)     |
| add_x_21       | DW01_inc       | width=8    | add_227 (CONVEX.v:227)     |
| add_x_22       | DW01_inc       | width=9    | add_238 (CONVEX.v:238)     |
| gt_x_24        | DW_cmp         | width=8    | gt_270 (CONVEX.v:270)      |
| add_x_25       | DW01_inc       | width=8    | add_286 (CONVEX.v:286)     |
| add_x_27       | DW01_inc       | width=4    | add_297 (CONVEX.v:297)     |
| lte_x_4726     | DW_cmp         | width=24   | lte_473 (CONVEX.v:473)     |
| add_x_4727     | DW01_inc       | width=2    | add_474 (CONVEX.v:474)     |
| add_x_4728     | DW01_inc       | width=2    | add_475_3 (CONVEX.v:475)   |
| add_x_4995     | DW01_inc       | width=7    | add_525 (CONVEX.v:525)     |
| lte_x_5241     | DW_cmp         | width=8    | lte_405 (CONVEX.v:405)     |
|                |                |            | lte_442 (CONVEX.v:442)     |
| eq_x_5242      | DW_cmp         | width=9    | eq_100 (CONVEX.v:100)      |
|                |                |            | eq_239 (CONVEX.v:239)      |
| gt_x_5243      | DW_cmp         | width=8    | gt_378 (CONVEX.v:378)      |
|                |                |            | gt_411 (CONVEX.v:411)      |
|                |                |            | gt_448 (CONVEX.v:448)      |
|                |                |            | gt_523 (CONVEX.v:523)      |
| lt_x_5244      | DW_cmp         | width=8    | lt_401 (CONVEX.v:401)      |
|                |                |            | lt_438 (CONVEX.v:438)      |
| eq_x_5245      | DW_cmp         | width=8    | eq_403 (CONVEX.v:403)      |
|                |                |            | eq_440 (CONVEX.v:440)      |
| gt_x_5246      | DW_cmp         | width=8    | gt_541 (CONVEX.v:541)      |
|                |                |            | gt_554 (CONVEX.v:554)      |
|                |                |            | gt_566 (CONVEX.v:566)      |
| rem_38         | DW_div_uns     | a_width=8  | rem_369 (CONVEX.v:369)     |
|                |                | b_width=8  | rem_387 (CONVEX.v:387)     |
| add_x_39       | DW01_inc       | width=9    | add_218 (CONVEX.v:218)     |
|                |                |            | add_369 (CONVEX.v:369)     |
|                |                |            | add_387 (CONVEX.v:387)     |
|                |                |            | add_404 (CONVEX.v:404)     |
|                |                |            | add_406 (CONVEX.v:406)     |
|                |                |            | add_417 (CONVEX.v:417)     |
|                |                |            | add_419 (CONVEX.v:419)     |
|                |                |            | add_441 (CONVEX.v:441)     |
|                |                |            | add_443 (CONVEX.v:443)     |
|                |                |            | add_454 (CONVEX.v:454)     |
|                |                |            | add_456 (CONVEX.v:456)     |
| add_x_6        | DW01_inc       | width=9    | add_123 (CONVEX.v:123)     |
|                |                |            | add_123_2 (CONVEX.v:123)   |
|                |                |            | add_249 (CONVEX.v:249)     |
|                |                |            | add_475 (CONVEX.v:475)     |
|                |                |            | add_475_2 (CONVEX.v:475)   |
| sub_x_46       | DW01_sub       | width=8    | sub_413 (CONVEX.v:413)     |
|                |                |            | sub_450 (CONVEX.v:450)     |
| add_x_47       | DW01_add       | width=8    | add_419_2 (CONVEX.v:419)   |
|                |                |            | add_456_2 (CONVEX.v:456)   |
| sub_x_29       | DW01_dec       | width=10   | sub_318 (CONVEX.v:318)     |
|                |                |            | sub_342 (CONVEX.v:342)     |
| sub_x_5000     | DW01_dec       | width=8    | sub_541 (CONVEX.v:541)     |
|                |                |            | sub_554 (CONVEX.v:554)     |
| rem_7          | DW_div_uns     | a_width=9  | rem_123 (CONVEX.v:123)     |
|                |                | b_width=8  | rem_123_2 (CONVEX.v:123)   |
|                |                |            | rem_475 (CONVEX.v:475)     |
|                |                |            | rem_475_2 (CONVEX.v:475)   |
| rem_40         | DW_div_uns     | a_width=9  | rem_369_2 (CONVEX.v:369)   |
|                |                | b_width=8  | rem_387_2 (CONVEX.v:387)   |
| *cell*1013     | DW_thermdec    | width=8    | gt_398_I10 (CONVEX.v:398)  |
|                |                |            | gt_398_I100 (CONVEX.v:398) |
|                |                |            | gt_398_I101 (CONVEX.v:398) |
|                |                |            | gt_398_I102 (CONVEX.v:398) |
|                |                |            | gt_398_I103 (CONVEX.v:398) |
|                |                |            | gt_398_I104 (CONVEX.v:398) |
|                |                |            | gt_398_I105 (CONVEX.v:398) |
|                |                |            | gt_398_I106 (CONVEX.v:398) |
|                |                |            | gt_398_I107 (CONVEX.v:398) |
|                |                |            | gt_398_I108 (CONVEX.v:398) |
|                |                |            | gt_398_I109 (CONVEX.v:398) |
|                |                |            | gt_398_I11 (CONVEX.v:398)  |
|                |                |            | gt_398_I110 (CONVEX.v:398) |
|                |                |            | gt_398_I111 (CONVEX.v:398) |
|                |                |            | gt_398_I112 (CONVEX.v:398) |
|                |                |            | gt_398_I113 (CONVEX.v:398) |
|                |                |            | gt_398_I114 (CONVEX.v:398) |
|                |                |            | gt_398_I115 (CONVEX.v:398) |
|                |                |            | gt_398_I116 (CONVEX.v:398) |
|                |                |            | gt_398_I117 (CONVEX.v:398) |
|                |                |            | gt_398_I118 (CONVEX.v:398) |
|                |                |            | gt_398_I119 (CONVEX.v:398) |
|                |                |            | gt_398_I12 (CONVEX.v:398)  |
|                |                |            | gt_398_I120 (CONVEX.v:398) |
|                |                |            | gt_398_I121 (CONVEX.v:398) |
|                |                |            | gt_398_I122 (CONVEX.v:398) |
|                |                |            | gt_398_I123 (CONVEX.v:398) |
|                |                |            | gt_398_I124 (CONVEX.v:398) |
|                |                |            | gt_398_I125 (CONVEX.v:398) |
|                |                |            | gt_398_I126 (CONVEX.v:398) |
|                |                |            | gt_398_I127 (CONVEX.v:398) |
|                |                |            | gt_398_I128 (CONVEX.v:398) |
|                |                |            | gt_398_I129 (CONVEX.v:398) |
|                |                |            | gt_398_I13 (CONVEX.v:398)  |
|                |                |            | gt_398_I14 (CONVEX.v:398)  |
|                |                |            | gt_398_I15 (CONVEX.v:398)  |
|                |                |            | gt_398_I16 (CONVEX.v:398)  |
|                |                |            | gt_398_I17 (CONVEX.v:398)  |
|                |                |            | gt_398_I18 (CONVEX.v:398)  |
|                |                |            | gt_398_I19 (CONVEX.v:398)  |
|                |                |            | gt_398_I2 (CONVEX.v:398)   |
|                |                |            | gt_398_I20 (CONVEX.v:398)  |
|                |                |            | gt_398_I21 (CONVEX.v:398)  |
|                |                |            | gt_398_I22 (CONVEX.v:398)  |
|                |                |            | gt_398_I23 (CONVEX.v:398)  |
|                |                |            | gt_398_I24 (CONVEX.v:398)  |
|                |                |            | gt_398_I25 (CONVEX.v:398)  |
|                |                |            | gt_398_I26 (CONVEX.v:398)  |
|                |                |            | gt_398_I27 (CONVEX.v:398)  |
|                |                |            | gt_398_I28 (CONVEX.v:398)  |
|                |                |            | gt_398_I29 (CONVEX.v:398)  |
|                |                |            | gt_398_I3 (CONVEX.v:398)   |
|                |                |            | gt_398_I30 (CONVEX.v:398)  |
|                |                |            | gt_398_I31 (CONVEX.v:398)  |
|                |                |            | gt_398_I32 (CONVEX.v:398)  |
|                |                |            | gt_398_I33 (CONVEX.v:398)  |
|                |                |            | gt_398_I34 (CONVEX.v:398)  |
|                |                |            | gt_398_I35 (CONVEX.v:398)  |
|                |                |            | gt_398_I36 (CONVEX.v:398)  |
|                |                |            | gt_398_I37 (CONVEX.v:398)  |
|                |                |            | gt_398_I38 (CONVEX.v:398)  |
|                |                |            | gt_398_I39 (CONVEX.v:398)  |
|                |                |            | gt_398_I4 (CONVEX.v:398)   |
|                |                |            | gt_398_I40 (CONVEX.v:398)  |
|                |                |            | gt_398_I41 (CONVEX.v:398)  |
|                |                |            | gt_398_I42 (CONVEX.v:398)  |
|                |                |            | gt_398_I43 (CONVEX.v:398)  |
|                |                |            | gt_398_I44 (CONVEX.v:398)  |
|                |                |            | gt_398_I45 (CONVEX.v:398)  |
|                |                |            | gt_398_I46 (CONVEX.v:398)  |
|                |                |            | gt_398_I47 (CONVEX.v:398)  |
|                |                |            | gt_398_I48 (CONVEX.v:398)  |
|                |                |            | gt_398_I49 (CONVEX.v:398)  |
|                |                |            | gt_398_I5 (CONVEX.v:398)   |
|                |                |            | gt_398_I50 (CONVEX.v:398)  |
|                |                |            | gt_398_I51 (CONVEX.v:398)  |
|                |                |            | gt_398_I52 (CONVEX.v:398)  |
|                |                |            | gt_398_I53 (CONVEX.v:398)  |
|                |                |            | gt_398_I54 (CONVEX.v:398)  |
|                |                |            | gt_398_I55 (CONVEX.v:398)  |
|                |                |            | gt_398_I56 (CONVEX.v:398)  |
|                |                |            | gt_398_I57 (CONVEX.v:398)  |
|                |                |            | gt_398_I58 (CONVEX.v:398)  |
|                |                |            | gt_398_I59 (CONVEX.v:398)  |
|                |                |            | gt_398_I6 (CONVEX.v:398)   |
|                |                |            | gt_398_I60 (CONVEX.v:398)  |
|                |                |            | gt_398_I61 (CONVEX.v:398)  |
|                |                |            | gt_398_I62 (CONVEX.v:398)  |
|                |                |            | gt_398_I63 (CONVEX.v:398)  |
|                |                |            | gt_398_I64 (CONVEX.v:398)  |
|                |                |            | gt_398_I65 (CONVEX.v:398)  |
|                |                |            | gt_398_I66 (CONVEX.v:398)  |
|                |                |            | gt_398_I67 (CONVEX.v:398)  |
|                |                |            | gt_398_I68 (CONVEX.v:398)  |
|                |                |            | gt_398_I69 (CONVEX.v:398)  |
|                |                |            | gt_398_I7 (CONVEX.v:398)   |
|                |                |            | gt_398_I70 (CONVEX.v:398)  |
|                |                |            | gt_398_I71 (CONVEX.v:398)  |
|                |                |            | gt_398_I72 (CONVEX.v:398)  |
|                |                |            | gt_398_I73 (CONVEX.v:398)  |
|                |                |            | gt_398_I74 (CONVEX.v:398)  |
|                |                |            | gt_398_I75 (CONVEX.v:398)  |
|                |                |            | gt_398_I76 (CONVEX.v:398)  |
|                |                |            | gt_398_I77 (CONVEX.v:398)  |
|                |                |            | gt_398_I78 (CONVEX.v:398)  |
|                |                |            | gt_398_I79 (CONVEX.v:398)  |
|                |                |            | gt_398_I8 (CONVEX.v:398)   |
|                |                |            | gt_398_I80 (CONVEX.v:398)  |
|                |                |            | gt_398_I81 (CONVEX.v:398)  |
|                |                |            | gt_398_I82 (CONVEX.v:398)  |
|                |                |            | gt_398_I83 (CONVEX.v:398)  |
|                |                |            | gt_398_I84 (CONVEX.v:398)  |
|                |                |            | gt_398_I85 (CONVEX.v:398)  |
|                |                |            | gt_398_I86 (CONVEX.v:398)  |
|                |                |            | gt_398_I87 (CONVEX.v:398)  |
|                |                |            | gt_398_I88 (CONVEX.v:398)  |
|                |                |            | gt_398_I89 (CONVEX.v:398)  |
|                |                |            | gt_398_I9 (CONVEX.v:398)   |
|                |                |            | gt_398_I90 (CONVEX.v:398)  |
|                |                |            | gt_398_I91 (CONVEX.v:398)  |
|                |                |            | gt_398_I92 (CONVEX.v:398)  |
|                |                |            | gt_398_I93 (CONVEX.v:398)  |
|                |                |            | gt_398_I94 (CONVEX.v:398)  |
|                |                |            | gt_398_I95 (CONVEX.v:398)  |
|                |                |            | gt_398_I96 (CONVEX.v:398)  |
|                |                |            | gt_398_I97 (CONVEX.v:398)  |
|                |                |            | gt_398_I98 (CONVEX.v:398)  |
|                |                |            | gt_398_I99 (CONVEX.v:398)  |
|                |                |            | gt_435_I10 (CONVEX.v:435)  |
|                |                |            | gt_435_I100 (CONVEX.v:435) |
|                |                |            | gt_435_I101 (CONVEX.v:435) |
|                |                |            | gt_435_I102 (CONVEX.v:435) |
|                |                |            | gt_435_I103 (CONVEX.v:435) |
|                |                |            | gt_435_I104 (CONVEX.v:435) |
|                |                |            | gt_435_I105 (CONVEX.v:435) |
|                |                |            | gt_435_I106 (CONVEX.v:435) |
|                |                |            | gt_435_I107 (CONVEX.v:435) |
|                |                |            | gt_435_I108 (CONVEX.v:435) |
|                |                |            | gt_435_I109 (CONVEX.v:435) |
|                |                |            | gt_435_I11 (CONVEX.v:435)  |
|                |                |            | gt_435_I110 (CONVEX.v:435) |
|                |                |            | gt_435_I111 (CONVEX.v:435) |
|                |                |            | gt_435_I112 (CONVEX.v:435) |
|                |                |            | gt_435_I113 (CONVEX.v:435) |
|                |                |            | gt_435_I114 (CONVEX.v:435) |
|                |                |            | gt_435_I115 (CONVEX.v:435) |
|                |                |            | gt_435_I116 (CONVEX.v:435) |
|                |                |            | gt_435_I117 (CONVEX.v:435) |
|                |                |            | gt_435_I118 (CONVEX.v:435) |
|                |                |            | gt_435_I119 (CONVEX.v:435) |
|                |                |            | gt_435_I12 (CONVEX.v:435)  |
|                |                |            | gt_435_I120 (CONVEX.v:435) |
|                |                |            | gt_435_I121 (CONVEX.v:435) |
|                |                |            | gt_435_I122 (CONVEX.v:435) |
|                |                |            | gt_435_I123 (CONVEX.v:435) |
|                |                |            | gt_435_I124 (CONVEX.v:435) |
|                |                |            | gt_435_I125 (CONVEX.v:435) |
|                |                |            | gt_435_I126 (CONVEX.v:435) |
|                |                |            | gt_435_I127 (CONVEX.v:435) |
|                |                |            | gt_435_I128 (CONVEX.v:435) |
|                |                |            | gt_435_I129 (CONVEX.v:435) |
|                |                |            | gt_435_I13 (CONVEX.v:435)  |
|                |                |            | gt_435_I14 (CONVEX.v:435)  |
|                |                |            | gt_435_I15 (CONVEX.v:435)  |
|                |                |            | gt_435_I16 (CONVEX.v:435)  |
|                |                |            | gt_435_I17 (CONVEX.v:435)  |
|                |                |            | gt_435_I18 (CONVEX.v:435)  |
|                |                |            | gt_435_I19 (CONVEX.v:435)  |
|                |                |            | gt_435_I2 (CONVEX.v:435)   |
|                |                |            | gt_435_I20 (CONVEX.v:435)  |
|                |                |            | gt_435_I21 (CONVEX.v:435)  |
|                |                |            | gt_435_I22 (CONVEX.v:435)  |
|                |                |            | gt_435_I23 (CONVEX.v:435)  |
|                |                |            | gt_435_I24 (CONVEX.v:435)  |
|                |                |            | gt_435_I25 (CONVEX.v:435)  |
|                |                |            | gt_435_I26 (CONVEX.v:435)  |
|                |                |            | gt_435_I27 (CONVEX.v:435)  |
|                |                |            | gt_435_I28 (CONVEX.v:435)  |
|                |                |            | gt_435_I29 (CONVEX.v:435)  |
|                |                |            | gt_435_I3 (CONVEX.v:435)   |
|                |                |            | gt_435_I30 (CONVEX.v:435)  |
|                |                |            | gt_435_I31 (CONVEX.v:435)  |
|                |                |            | gt_435_I32 (CONVEX.v:435)  |
|                |                |            | gt_435_I33 (CONVEX.v:435)  |
|                |                |            | gt_435_I34 (CONVEX.v:435)  |
|                |                |            | gt_435_I35 (CONVEX.v:435)  |
|                |                |            | gt_435_I36 (CONVEX.v:435)  |
|                |                |            | gt_435_I37 (CONVEX.v:435)  |
|                |                |            | gt_435_I38 (CONVEX.v:435)  |
|                |                |            | gt_435_I39 (CONVEX.v:435)  |
|                |                |            | gt_435_I4 (CONVEX.v:435)   |
|                |                |            | gt_435_I40 (CONVEX.v:435)  |
|                |                |            | gt_435_I41 (CONVEX.v:435)  |
|                |                |            | gt_435_I42 (CONVEX.v:435)  |
|                |                |            | gt_435_I43 (CONVEX.v:435)  |
|                |                |            | gt_435_I44 (CONVEX.v:435)  |
|                |                |            | gt_435_I45 (CONVEX.v:435)  |
|                |                |            | gt_435_I46 (CONVEX.v:435)  |
|                |                |            | gt_435_I47 (CONVEX.v:435)  |
|                |                |            | gt_435_I48 (CONVEX.v:435)  |
|                |                |            | gt_435_I49 (CONVEX.v:435)  |
|                |                |            | gt_435_I5 (CONVEX.v:435)   |
|                |                |            | gt_435_I50 (CONVEX.v:435)  |
|                |                |            | gt_435_I51 (CONVEX.v:435)  |
|                |                |            | gt_435_I52 (CONVEX.v:435)  |
|                |                |            | gt_435_I53 (CONVEX.v:435)  |
|                |                |            | gt_435_I54 (CONVEX.v:435)  |
|                |                |            | gt_435_I55 (CONVEX.v:435)  |
|                |                |            | gt_435_I56 (CONVEX.v:435)  |
|                |                |            | gt_435_I57 (CONVEX.v:435)  |
|                |                |            | gt_435_I58 (CONVEX.v:435)  |
|                |                |            | gt_435_I59 (CONVEX.v:435)  |
|                |                |            | gt_435_I6 (CONVEX.v:435)   |
|                |                |            | gt_435_I60 (CONVEX.v:435)  |
|                |                |            | gt_435_I61 (CONVEX.v:435)  |
|                |                |            | gt_435_I62 (CONVEX.v:435)  |
|                |                |            | gt_435_I63 (CONVEX.v:435)  |
|                |                |            | gt_435_I64 (CONVEX.v:435)  |
|                |                |            | gt_435_I65 (CONVEX.v:435)  |
|                |                |            | gt_435_I66 (CONVEX.v:435)  |
|                |                |            | gt_435_I67 (CONVEX.v:435)  |
|                |                |            | gt_435_I68 (CONVEX.v:435)  |
|                |                |            | gt_435_I69 (CONVEX.v:435)  |
|                |                |            | gt_435_I7 (CONVEX.v:435)   |
|                |                |            | gt_435_I70 (CONVEX.v:435)  |
|                |                |            | gt_435_I71 (CONVEX.v:435)  |
|                |                |            | gt_435_I72 (CONVEX.v:435)  |
|                |                |            | gt_435_I73 (CONVEX.v:435)  |
|                |                |            | gt_435_I74 (CONVEX.v:435)  |
|                |                |            | gt_435_I75 (CONVEX.v:435)  |
|                |                |            | gt_435_I76 (CONVEX.v:435)  |
|                |                |            | gt_435_I77 (CONVEX.v:435)  |
|                |                |            | gt_435_I78 (CONVEX.v:435)  |
|                |                |            | gt_435_I79 (CONVEX.v:435)  |
|                |                |            | gt_435_I8 (CONVEX.v:435)   |
|                |                |            | gt_435_I80 (CONVEX.v:435)  |
|                |                |            | gt_435_I81 (CONVEX.v:435)  |
|                |                |            | gt_435_I82 (CONVEX.v:435)  |
|                |                |            | gt_435_I83 (CONVEX.v:435)  |
|                |                |            | gt_435_I84 (CONVEX.v:435)  |
|                |                |            | gt_435_I85 (CONVEX.v:435)  |
|                |                |            | gt_435_I86 (CONVEX.v:435)  |
|                |                |            | gt_435_I87 (CONVEX.v:435)  |
|                |                |            | gt_435_I88 (CONVEX.v:435)  |
|                |                |            | gt_435_I89 (CONVEX.v:435)  |
|                |                |            | gt_435_I9 (CONVEX.v:435)   |
|                |                |            | gt_435_I90 (CONVEX.v:435)  |
|                |                |            | gt_435_I91 (CONVEX.v:435)  |
|                |                |            | gt_435_I92 (CONVEX.v:435)  |
|                |                |            | gt_435_I93 (CONVEX.v:435)  |
|                |                |            | gt_435_I94 (CONVEX.v:435)  |
|                |                |            | gt_435_I95 (CONVEX.v:435)  |
|                |                |            | gt_435_I96 (CONVEX.v:435)  |
|                |                |            | gt_435_I97 (CONVEX.v:435)  |
|                |                |            | gt_435_I98 (CONVEX.v:435)  |
|                |                |            | gt_435_I99 (CONVEX.v:435)  |
| DP_OP_11844J1_122_9068          |            |                            |
|                | DP_OP_11844J1_122_9068 |    |                            |
| DP_OP_11845J1_123_8605          |            |                            |
|                | DP_OP_11845J1_123_8605 |    |                            |
| DP_OP_73_131_3948               |            |                            |
|                | DP_OP_73_131_3948 |         |                            |
| DP_OP_74_132_3948               |            |                            |
|                | DP_OP_74_132_3948 |         |                            |
| DP_OP_11851J1_127_7261          |            |                            |
|                | DP_OP_11851J1_127_7261 |    |                            |
=============================================================================

Datapath Report for DP_OP_11844J1_122_9068
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_11844J1_122_9068 | sub_109_C123 (CONVEX.v:109)                       |
|                      | mult_113_C123 (CONVEX.v:113)                        |
|                      | sub_110_C123 (CONVEX.v:110)                         |
|                      | sub_115_C123 (CONVEX.v:115)                         |
|                      | mult_114_C123 (CONVEX.v:114)                        |
|                      | sub_111_C123 (CONVEX.v:111)                         |
|                      | sub_112_C123 (CONVEX.v:112)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 10    |                                          |
| I2    | PI   | Unsigned | 10    |                                          |
| I3    | PI   | Unsigned | 10    |                                          |
| I4    | PI   | Unsigned | 10    |                                          |
| I5    | PI   | Unsigned | 10    |                                          |
| I6    | PI   | Unsigned | 10    |                                          |
| T10   | IFO  | Signed   | 11    | I1 - I2 (CONVEX.v:109)                   |
| T11   | IFO  | Signed   | 11    | I3 - I4 (CONVEX.v:110)                   |
| T14   | IFO  | Signed   | 22    | T10 * T11 (CONVEX.v:113)                 |
| T12   | IFO  | Signed   | 11    | I5 - I4 (CONVEX.v:111)                   |
| T13   | IFO  | Signed   | 11    | I6 - I2 (CONVEX.v:112)                   |
| T15   | IFO  | Signed   | 22    | T12 * T13 (CONVEX.v:114)                 |
| O1    | PO   | Signed   | 23    | T14 - T15 (CONVEX.v:115)                 |
==============================================================================

Datapath Report for DP_OP_11845J1_123_8605
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_11845J1_123_8605 | sub_522 (CONVEX.v:522) add_378 (CONVEX.v:378)     |
|                      | sub_378 (CONVEX.v:378)                              |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 7     |                                          |
| I2    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Signed   | 7     | I1 - $unsigned(1'b1) ( CONVEX.v:378 CONVEX.v:522 ) |
| O2    | PO   | Unsigned | 7     | I2 + O1 (CONVEX.v:378)                   |
==============================================================================

Datapath Report for DP_OP_73_131_3948
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_73_131_3948    | add_387_S2 (CONVEX.v:387)                           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 7     |                                          |
| O1    | PO   | Unsigned | 7     | I1 + $unsigned(2'b10) (CONVEX.v:387)     |
==============================================================================

Datapath Report for DP_OP_74_132_3948
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_74_132_3948    | add_388 (CONVEX.v:388)                              |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 7     |                                          |
| O1    | PO   | Unsigned | 7     | I1 + $unsigned(1'b1) (CONVEX.v:388)      |
==============================================================================

Datapath Report for DP_OP_11851J1_127_7261
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_11851J1_127_7261 | sub_273 (CONVEX.v:273) sub_266 (CONVEX.v:266)     |
|                      | add_266 (CONVEX.v:266) sub_270_S2 (CONVEX.v:270)    |
|                      | sub_270_S2_2 (CONVEX.v:270) C148369 (CONVEX.v:270)  |
|                      | C148368 (CONVEX.v:262) C148370 (CONVEX.v:260)       |
|                      | add_264 (CONVEX.v:264)                              |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 1     |                                          |
| I4    | PI   | Unsigned | 1     |                                          |
| I5    | PI   | Unsigned | 2     |                                          |
| T11848 | IFO | Unsigned | 8     | { I3, I4 } ? O1 : I1 ( CONVEX.v:260 CONVEX.v:262 CONVEX.v:270 ) |
| O1    | PO   | Signed   | 8     | I1 - I2 ( CONVEX.v:266 CONVEX.v:270 CONVEX.v:273 ) |
| O2    | PO   | Unsigned | 8     | I5 + T11848 ( CONVEX.v:264 CONVEX.v:266 CONVEX.v:270 ) |
==============================================================================


Resource Report for Ungrouped Hierarchy rem_7
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
=============================================================================


Resource Report for Ungrouped Hierarchy rem_38
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
=============================================================================


Resource Report for Ungrouped Hierarchy rem_40
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
=============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'lte_97 (CONVEX.v:97)' in design 'CONVEX' breaks the datapath extraction because there is leakage due to driver(signed)/load(unsigned) sign mismatch on fanin from operator of resources 'sub_97 (CONVEX.v:97)'.  (HDL-120)

Information: The output of subtractor associated with resources 'sub_97 (CONVEX.v:97)' is treated as signed signal. (HDL-132)

Information: Operator associated with resources 'add_378 (CONVEX.v:378) sub_378 (CONVEX.v:378)' in design 'CONVEX' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C148382 (CONVEX.v:378)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| sub_x_1            | DW01_dec         | apparch (area)     |                |
| lte_x_2            | DW_cmp           | apparch (area)     |                |
| lt_x_3             | DW_cmp           | apparch (area)     |                |
| gte_x_4            | DW_cmp           | apparch (area)     |                |
| add_x_18           | DW01_inc         | apparch (area)     |                |
| add_x_21           | DW01_inc         | apparch (area)     |                |
| add_x_22           | DW01_inc         | apparch (area)     |                |
| gt_x_24            | DW_cmp           | apparch (area)     |                |
| add_x_25           | DW01_inc         | apparch (area)     |                |
| add_x_27           | DW01_inc         | apparch (area)     |                |
| lte_x_4726         | DW_cmp           | apparch (area)     |                |
| add_x_4727         | DW01_inc         | apparch (area)     |                |
| add_x_4728         | DW01_inc         | apparch (area)     |                |
| add_x_4995         | DW01_inc         | apparch (area)     |                |
| lte_x_5241         | DW_cmp           | apparch (area)     |                |
| eq_x_5242          | DW_cmp           | apparch (area)     |                |
| gt_x_5243          | DW_cmp           | apparch (area)     |                |
| lt_x_5244          | DW_cmp           | apparch (area)     |                |
| eq_x_5245          | DW_cmp           | apparch (area)     |                |
| gt_x_5246          | DW_cmp           | apparch (area)     |                |
| rem_38             | DW_div_uns       | cla                |                |
| add_x_39           | DW01_inc         | pparch (area,speed)                 |
| add_x_6            | DW01_inc         | pparch (area,speed)                 |
| sub_x_46           | DW01_sub         | apparch (area)     |                |
| add_x_47           | DW01_add         | apparch (area)     |                |
| sub_x_29           | DW01_dec         | apparch (area)     |                |
| sub_x_5000         | DW01_dec         | apparch (area)     |                |
| rem_7              | DW_div_uns       | cla2               |                |
| rem_40             | DW_div_uns       | cla                |                |
| *cell*1013         | DW_thermdec      | cgen (area)        |                |
| DP_OP_11844J1_122_9068                |                    |                |
|                    | DP_OP_11844J1_122_9068 | str (area,speed)              |
|                    |                  | mult_arch: benc_radix4              |
| DP_OP_11845J1_123_8605                |                    |                |
|                    | DP_OP_11845J1_123_8605 | str (area)   |                |
| DP_OP_73_131_3948  | DP_OP_73_131_3948 | str (area)        |                |
| DP_OP_74_132_3948  | DP_OP_74_132_3948 | str (area)        |                |
| DP_OP_11851J1_127_7261                |                    |                |
|                    | DP_OP_11851J1_127_7261 | str (area)   |                |
===============================================================================

1
