###############################################################
#  Generated by:      Cadence Innovus 20.15-s105_1
#  OS:                Linux x86_64(Host ID ee21)
#  Generated on:      Mon Jul 31 20:58:48 2023
#  Design:            CHIP
#  Command:           saveIoFile -byOrder CHIP.io
###############################################################

###############################################################
#  You can modify by your own
#  You can modify by your own
#  You can modify by your own
###############################################################

# Syntax: (inst  name="PAD_NAME"	  place_status=placed )
#(endspace gap=50)

(globals
    version = 3
    io_order = default
)

(iopad
    (top
    (inst  name="VDDP0"	place_status=placed )
    (inst  name="GNDP0"	place_status=placed )
    (inst  name="I_DELAY0"	place_status=placed )
    (inst  name="VDDC0"	place_status=placed )

    (inst  name="GNDC0"	place_status=placed )
    (inst  name="I_DELAY1"	place_status=placed )
    (inst  name="VDDC1"	place_status=placed )
    (inst  name="GNDC1"	place_status=placed )
    (inst  name="I_CLK"	place_status=placed )

    (inst  name="VDDC2"	place_status=placed )
	(inst  name="GNDC2"	place_status=placed )
    (inst  name="I_DELAY2"	place_status=placed )
    (inst  name="I_SOURCE0"	place_status=placed )
    (inst  name="VDDC3"	place_status=placed )

    (inst  name="GNDC3"	place_status=placed )
    (inst  name="I_DELAY3"	place_status=placed )
    (inst  name="I_SOURCE1"	place_status=placed )
    (inst  name="VDDP1"	place_status=placed )
    (inst  name="GNDP1"	place_status=placed )

    )
    (left

    (inst  name="VDDP2"	place_status=placed )
    (inst  name="GNDP2"	place_status=placed )
    (inst  name="I_SOURCE2"	place_status=placed )
    (inst  name="VDDC4"	place_status=placed )
    (inst  name="GNDC4"	place_status=placed )

    (inst  name="I_SOURCE3"	place_status=placed )
    (inst  name="VDDC5"	place_status=placed )
    (inst  name="GNDC5"	place_status=placed )
    (inst  name="I_DESTINATION0"	place_status=placed )
    (inst  name="I_DESTINATION1"	place_status=placed )

    (inst  name="VDDC6"	place_status=placed )
    (inst  name="GNDC6"	place_status=placed )
    (inst  name="I_DESTINATION2"	place_status=placed )
	(inst  name="I_DESTINATION3"	place_status=placed )
    (inst  name="VDDC7"	place_status=placed )

	(inst  name="GNDC7"	place_status=placed )
    (inst  name="I_IN_VALID"	place_status=placed )
    (inst  name="VDDP3"	place_status=placed )
    (inst  name="GNDP3"	place_status=placed )

    )
    (bottom

	(inst  name="VDDP4"	place_status=placed )
    (inst  name="GNDP4"	place_status=placed )
    (inst  name="O_WORST0"	place_status=placed )
    (inst  name="VDDC8"	place_status=placed )
	(inst  name="GNDC8"	place_status=placed )

    (inst  name="O_WORST1"	place_status=placed )
    (inst  name="VDDC9"	place_status=placed )
	(inst  name="GNDC9"	place_status=placed )
    (inst  name="O_WORST2"	place_status=placed )
    (inst  name="VDDC10"	place_status=placed )

    (inst  name="GNDC10"	place_status=placed )
    (inst  name="I_RST"	place_status=placed )
    (inst  name="VDDC11"	place_status=placed )
    (inst  name="GNDC11"	place_status=placed )
    (inst  name="O_WORST3"	place_status=placed )

    (inst  name="O_WORST4"	place_status=placed )
    (inst  name="O_WORST5"	place_status=placed )
    (inst  name="VDDP5"	place_status=placed )
    (inst  name="GNDP5"	place_status=placed )


    )
    (right
    
    (inst  name="VDDP6"	place_status=placed )
    (inst  name="GNDP6"	place_status=placed )
    (inst  name="O_WORST6"	place_status=placed )
    (inst  name="VDDC12"	place_status=placed )
    (inst  name="GNDC12"	place_status=placed )

    (inst  name="O_WORST7"	place_status=placed )
    (inst  name="VDDC13"	place_status=placed )
	(inst  name="GNDC13"	place_status=placed )
	(inst  name="O_PATH0"	place_status=placed )
	(inst  name="O_PATH1"	place_status=placed )

    (inst  name="VDDC14"	place_status=placed )
    (inst  name="GNDC14"	place_status=placed )
	(inst  name="O_VALID"	place_status=placed )
    (inst  name="VDDC15"	place_status=placed )
    (inst  name="GNDC15"	place_status=placed )
    
	(inst  name="O_PATH2"	place_status=placed )
	(inst  name="O_PATH3"	place_status=placed )	
    (inst  name="VDDP7"	place_status=placed )
    (inst  name="GNDP7"	place_status=placed )

    )
	(topright
        (inst  name="topright"        cell="CORNERD" )
    )
        (topleft
        (inst  name="topleft"         cell="CORNERD" )
    )
        (bottomright
        (inst  name="bottomright"     cell="CORNERD" )
    )
        (bottomleft
        (inst  name="bottomleft"      cell="CORNERD" )
    )
)

