 
****************************************
Report : resources
Design : MPCA
Version: T-2022.03
Date   : Mon Sep 15 00:18:43 2025
****************************************


Resource Report for this hierarchy in file ../01_RTL/MPCA.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| eq_x_2         | DW_cmp         | width=2    | eq_293 (MPCA.v:293)        |
| eq_x_3         | DW_cmp         | width=2    | eq_293_3 (MPCA.v:293)      |
| eq_x_4         | DW_cmp         | width=2    | eq_293_5 (MPCA.v:293)      |
| eq_x_5         | DW_cmp         | width=2    | eq_293_7 (MPCA.v:293)      |
| eq_x_6         | DW_cmp         | width=2    | eq_293_9 (MPCA.v:293)      |
| eq_x_7         | DW_cmp         | width=2    | eq_293_11 (MPCA.v:293)     |
| eq_x_8         | DW_cmp         | width=2    | eq_293_13 (MPCA.v:293)     |
| eq_x_9         | DW_cmp         | width=2    | eq_293_15 (MPCA.v:293)     |
| add_x_101      | DW01_add       | width=16   | D76/add_508 (MPCA.v:508)   |
| gt_x_115       | DW_cmp         | width=4    | maskpack0/gt_720 (MPCA.v:720) |
| add_x_124      | DW01_inc       | width=2    | alloc0/add_783 (MPCA.v:783) |
| lte_x_128      | DW_cmp         | width=2    | alloc0/lte_801 (MPCA.v:801) |
| lte_x_129      | DW_cmp         | width=3    | alloc0/lte_813 (MPCA.v:813) |
| eq_x_130       | DW_cmp         | width=3    | alloc0/eq_813 (MPCA.v:813) |
| lte_x_131      | DW_cmp         | width=3    | alloc0/lte_818 (MPCA.v:818) |
| eq_x_132       | DW_cmp         | width=3    | alloc0/eq_818 (MPCA.v:818) |
| lte_x_133      | DW_cmp         | width=3    | alloc0/lte_823 (MPCA.v:823) |
| eq_x_134       | DW_cmp         | width=3    | alloc0/eq_823 (MPCA.v:823) |
| add_x_161      | DW01_add       | width=16   | D10/add_508 (MPCA.v:508)   |
| add_x_162      | DW01_add       | width=16   | D32/add_508 (MPCA.v:508)   |
| add_x_163      | DW01_add       | width=16   | D54/add_508 (MPCA.v:508)   |
| gt_x_265       | DW_cmp         | width=4    | maskpack7/gt_720 (MPCA.v:720) |
| gt_x_269       | DW_cmp         | width=4    | maskpack6/gt_720 (MPCA.v:720) |
| gt_x_273       | DW_cmp         | width=4    | maskpack5/gt_720 (MPCA.v:720) |
| gt_x_279       | DW_cmp         | width=4    | maskpack4/gt_720 (MPCA.v:720) |
| gt_x_285       | DW_cmp         | width=4    | maskpack3/gt_720 (MPCA.v:720) |
| gt_x_289       | DW_cmp         | width=4    | maskpack2/gt_720 (MPCA.v:720) |
| gt_x_293       | DW_cmp         | width=4    | maskpack1/gt_720 (MPCA.v:720) |
| add_x_296      | DW01_inc       | width=3    | alloc7/add_756 (MPCA.v:756) |
| add_x_297      | DW01_inc       | width=3    | alloc7/add_757 (MPCA.v:757) |
| add_x_298      | DW01_inc       | width=3    | alloc7/add_758 (MPCA.v:758) |
| lte_x_308      | DW_cmp         | width=2    | alloc7/lte_801 (MPCA.v:801) |
| lte_x_309      | DW_cmp         | width=3    | alloc7/lte_813 (MPCA.v:813) |
| eq_x_310       | DW_cmp         | width=3    | alloc7/eq_813 (MPCA.v:813) |
| lte_x_311      | DW_cmp         | width=3    | alloc7/lte_818 (MPCA.v:818) |
| eq_x_312       | DW_cmp         | width=3    | alloc7/eq_818 (MPCA.v:818) |
| lte_x_313      | DW_cmp         | width=3    | alloc7/lte_823 (MPCA.v:823) |
| eq_x_314       | DW_cmp         | width=3    | alloc7/eq_823 (MPCA.v:823) |
| add_x_347      | DW01_inc       | width=3    | alloc6/add_756 (MPCA.v:756) |
| add_x_348      | DW01_inc       | width=3    | alloc6/add_757 (MPCA.v:757) |
| add_x_349      | DW01_inc       | width=3    | alloc6/add_758 (MPCA.v:758) |
| add_x_356      | DW01_inc       | width=2    | alloc6/add_783 (MPCA.v:783) |
| lte_x_361      | DW_cmp         | width=2    | alloc6/lte_801 (MPCA.v:801) |
| lte_x_362      | DW_cmp         | width=3    | alloc6/lte_813 (MPCA.v:813) |
| eq_x_363       | DW_cmp         | width=3    | alloc6/eq_813 (MPCA.v:813) |
| lte_x_364      | DW_cmp         | width=3    | alloc6/lte_818 (MPCA.v:818) |
| eq_x_365       | DW_cmp         | width=3    | alloc6/eq_818 (MPCA.v:818) |
| lte_x_366      | DW_cmp         | width=3    | alloc6/lte_823 (MPCA.v:823) |
| eq_x_367       | DW_cmp         | width=3    | alloc6/eq_823 (MPCA.v:823) |
| add_x_396      | DW01_inc       | width=3    | alloc5/add_756 (MPCA.v:756) |
| add_x_397      | DW01_inc       | width=3    | alloc5/add_757 (MPCA.v:757) |
| add_x_398      | DW01_inc       | width=3    | alloc5/add_758 (MPCA.v:758) |
| add_x_405      | DW01_inc       | width=2    | alloc5/add_783 (MPCA.v:783) |
| lte_x_409      | DW_cmp         | width=2    | alloc5/lte_801 (MPCA.v:801) |
| lte_x_410      | DW_cmp         | width=3    | alloc5/lte_813 (MPCA.v:813) |
| eq_x_411       | DW_cmp         | width=3    | alloc5/eq_813 (MPCA.v:813) |
| lte_x_412      | DW_cmp         | width=3    | alloc5/lte_818 (MPCA.v:818) |
| eq_x_413       | DW_cmp         | width=3    | alloc5/eq_818 (MPCA.v:818) |
| lte_x_414      | DW_cmp         | width=3    | alloc5/lte_823 (MPCA.v:823) |
| eq_x_415       | DW_cmp         | width=3    | alloc5/eq_823 (MPCA.v:823) |
| add_x_444      | DW01_inc       | width=3    | alloc4/add_756 (MPCA.v:756) |
| add_x_445      | DW01_inc       | width=3    | alloc4/add_757 (MPCA.v:757) |
| add_x_446      | DW01_inc       | width=3    | alloc4/add_758 (MPCA.v:758) |
| add_x_453      | DW01_inc       | width=2    | alloc4/add_783 (MPCA.v:783) |
| lte_x_457      | DW_cmp         | width=2    | alloc4/lte_801 (MPCA.v:801) |
| lte_x_458      | DW_cmp         | width=3    | alloc4/lte_813 (MPCA.v:813) |
| eq_x_459       | DW_cmp         | width=3    | alloc4/eq_813 (MPCA.v:813) |
| lte_x_460      | DW_cmp         | width=3    | alloc4/lte_818 (MPCA.v:818) |
| eq_x_461       | DW_cmp         | width=3    | alloc4/eq_818 (MPCA.v:818) |
| lte_x_462      | DW_cmp         | width=3    | alloc4/lte_823 (MPCA.v:823) |
| eq_x_463       | DW_cmp         | width=3    | alloc4/eq_823 (MPCA.v:823) |
| add_x_506      | DW01_inc       | width=3    | alloc3/add_756 (MPCA.v:756) |
| add_x_507      | DW01_inc       | width=3    | alloc3/add_757 (MPCA.v:757) |
| add_x_508      | DW01_inc       | width=3    | alloc3/add_758 (MPCA.v:758) |
| add_x_515      | DW01_inc       | width=2    | alloc3/add_783 (MPCA.v:783) |
| lte_x_519      | DW_cmp         | width=2    | alloc3/lte_801 (MPCA.v:801) |
| lte_x_520      | DW_cmp         | width=3    | alloc3/lte_813 (MPCA.v:813) |
| eq_x_521       | DW_cmp         | width=3    | alloc3/eq_813 (MPCA.v:813) |
| lte_x_522      | DW_cmp         | width=3    | alloc3/lte_818 (MPCA.v:818) |
| eq_x_523       | DW_cmp         | width=3    | alloc3/eq_818 (MPCA.v:818) |
| lte_x_524      | DW_cmp         | width=3    | alloc3/lte_823 (MPCA.v:823) |
| eq_x_525       | DW_cmp         | width=3    | alloc3/eq_823 (MPCA.v:823) |
| add_x_554      | DW01_inc       | width=3    | alloc2/add_756 (MPCA.v:756) |
| add_x_555      | DW01_inc       | width=3    | alloc2/add_757 (MPCA.v:757) |
| add_x_556      | DW01_inc       | width=3    | alloc2/add_758 (MPCA.v:758) |
| add_x_567      | DW01_inc       | width=2    | alloc2/add_783 (MPCA.v:783) |
| lte_x_572      | DW_cmp         | width=2    | alloc2/lte_801 (MPCA.v:801) |
| lte_x_573      | DW_cmp         | width=3    | alloc2/lte_813 (MPCA.v:813) |
| eq_x_574       | DW_cmp         | width=3    | alloc2/eq_813 (MPCA.v:813) |
| lte_x_575      | DW_cmp         | width=3    | alloc2/lte_818 (MPCA.v:818) |
| eq_x_576       | DW_cmp         | width=3    | alloc2/eq_818 (MPCA.v:818) |
| lte_x_577      | DW_cmp         | width=3    | alloc2/lte_823 (MPCA.v:823) |
| eq_x_578       | DW_cmp         | width=3    | alloc2/eq_823 (MPCA.v:823) |
| add_x_613      | DW01_inc       | width=3    | alloc1/add_756 (MPCA.v:756) |
| add_x_614      | DW01_inc       | width=3    | alloc1/add_757 (MPCA.v:757) |
| add_x_615      | DW01_inc       | width=3    | alloc1/add_758 (MPCA.v:758) |
| add_x_622      | DW01_inc       | width=2    | alloc1/add_783 (MPCA.v:783) |
| lte_x_626      | DW_cmp         | width=2    | alloc1/lte_801 (MPCA.v:801) |
| lte_x_627      | DW_cmp         | width=3    | alloc1/lte_813 (MPCA.v:813) |
| eq_x_628       | DW_cmp         | width=3    | alloc1/eq_813 (MPCA.v:813) |
| lte_x_629      | DW_cmp         | width=3    | alloc1/lte_818 (MPCA.v:818) |
| eq_x_630       | DW_cmp         | width=3    | alloc1/eq_818 (MPCA.v:818) |
| lte_x_631      | DW_cmp         | width=3    | alloc1/lte_823 (MPCA.v:823) |
| eq_x_632       | DW_cmp         | width=3    | alloc1/eq_823 (MPCA.v:823) |
| gt_x_665       | DW_cmp         | width=8    | packetsort/COM_9/gt_851 (MPCA.v:851) |
| lt_x_666       | DW_cmp         | width=8    | packetsort/COM_9/lt_855 (MPCA.v:855) |
| lt_x_667       | DW_cmp         | width=3    | packetsort/COM_9/lt_860 (MPCA.v:860) |
| gt_x_670       | DW_cmp         | width=8    | packetsort/COM_12/gt_851 (MPCA.v:851) |
| lt_x_671       | DW_cmp         | width=8    | packetsort/COM_12/lt_855 (MPCA.v:855) |
| lt_x_672       | DW_cmp         | width=3    | packetsort/COM_12/lt_860 (MPCA.v:860) |
| gt_x_677       | DW_cmp         | width=8    | packetsort/COM_17/gt_851 (MPCA.v:851) |
| lt_x_678       | DW_cmp         | width=8    | packetsort/COM_17/lt_855 (MPCA.v:855) |
| lt_x_679       | DW_cmp         | width=3    | packetsort/COM_17/lt_860 (MPCA.v:860) |
| gt_x_683       | DW_cmp         | width=8    | packetsort/COM_16/gt_851 (MPCA.v:851) |
| lt_x_684       | DW_cmp         | width=8    | packetsort/COM_16/lt_855 (MPCA.v:855) |
| lt_x_685       | DW_cmp         | width=3    | packetsort/COM_16/lt_860 (MPCA.v:860) |
| gt_x_690       | DW_cmp         | width=8    | packetsort/COM_15/gt_851 (MPCA.v:851) |
| lt_x_691       | DW_cmp         | width=8    | packetsort/COM_15/lt_855 (MPCA.v:855) |
| lt_x_692       | DW_cmp         | width=3    | packetsort/COM_15/lt_860 (MPCA.v:860) |
| gt_x_695       | DW_cmp         | width=8    | packetsort/COM_14/gt_851 (MPCA.v:851) |
| lt_x_696       | DW_cmp         | width=8    | packetsort/COM_14/lt_855 (MPCA.v:855) |
| lt_x_697       | DW_cmp         | width=3    | packetsort/COM_14/lt_860 (MPCA.v:860) |
| gt_x_700       | DW_cmp         | width=8    | packetsort/COM_13/gt_851 (MPCA.v:851) |
| lt_x_701       | DW_cmp         | width=8    | packetsort/COM_13/lt_855 (MPCA.v:855) |
| lt_x_702       | DW_cmp         | width=3    | packetsort/COM_13/lt_860 (MPCA.v:860) |
| gt_x_705       | DW_cmp         | width=8    | packetsort/COM_11/gt_851 (MPCA.v:851) |
| lt_x_706       | DW_cmp         | width=8    | packetsort/COM_11/lt_855 (MPCA.v:855) |
| lt_x_707       | DW_cmp         | width=3    | packetsort/COM_11/lt_860 (MPCA.v:860) |
| gt_x_710       | DW_cmp         | width=8    | packetsort/COM_10/gt_851 (MPCA.v:851) |
| lt_x_711       | DW_cmp         | width=8    | packetsort/COM_10/lt_855 (MPCA.v:855) |
| lt_x_712       | DW_cmp         | width=3    | packetsort/COM_10/lt_860 (MPCA.v:860) |
| gt_x_715       | DW_cmp         | width=8    | packetsort/COM_8/gt_851 (MPCA.v:851) |
| lt_x_716       | DW_cmp         | width=8    | packetsort/COM_8/lt_855 (MPCA.v:855) |
| lt_x_717       | DW_cmp         | width=3    | packetsort/COM_8/lt_860 (MPCA.v:860) |
| gt_x_720       | DW_cmp         | width=8    | packetsort/COM_7/gt_851 (MPCA.v:851) |
| lt_x_721       | DW_cmp         | width=8    | packetsort/COM_7/lt_855 (MPCA.v:855) |
| lt_x_722       | DW_cmp         | width=3    | packetsort/COM_7/lt_860 (MPCA.v:860) |
| gt_x_725       | DW_cmp         | width=8    | packetsort/COM_6/gt_851 (MPCA.v:851) |
| lt_x_726       | DW_cmp         | width=8    | packetsort/COM_6/lt_855 (MPCA.v:855) |
| lt_x_727       | DW_cmp         | width=3    | packetsort/COM_6/lt_860 (MPCA.v:860) |
| gt_x_730       | DW_cmp         | width=8    | packetsort/COM_5/gt_851 (MPCA.v:851) |
| lt_x_731       | DW_cmp         | width=8    | packetsort/COM_5/lt_855 (MPCA.v:855) |
| lt_x_732       | DW_cmp         | width=3    | packetsort/COM_5/lt_860 (MPCA.v:860) |
| gt_x_741       | DW_cmp         | width=8    | packetsort/COM_19/gt_851 (MPCA.v:851) |
| lt_x_742       | DW_cmp         | width=8    | packetsort/COM_19/lt_855 (MPCA.v:855) |
| lt_x_743       | DW_cmp         | width=3    | packetsort/COM_19/lt_860 (MPCA.v:860) |
| gt_x_746       | DW_cmp         | width=8    | packetsort/COM_18/gt_851 (MPCA.v:851) |
| lt_x_747       | DW_cmp         | width=8    | packetsort/COM_18/lt_855 (MPCA.v:855) |
| lt_x_748       | DW_cmp         | width=3    | packetsort/COM_18/lt_860 (MPCA.v:860) |
| add_x_99       | DW01_add       | width=16   | D10/add_506 (MPCA.v:506)   |
|                |                |            | D32/add_506 (MPCA.v:506)   |
|                |                |            | D54/add_506 (MPCA.v:506)   |
|                |                |            | D76/add_506 (MPCA.v:506)   |
| add_x_100      | DW01_add       | width=16   | D10/add_507 (MPCA.v:507)   |
|                |                |            | D32/add_507 (MPCA.v:507)   |
|                |                |            | D54/add_507 (MPCA.v:507)   |
|                |                |            | D76/add_507 (MPCA.v:507)   |
| DP_OP_1191J1_122_1817           |            |                            |
|                | DP_OP_1191J1_122_1817 |     |                            |
| DP_OP_1192J1_123_2215           |            |                            |
|                | DP_OP_1192J1_123_2215 |     |                            |
| DP_OP_1193J1_124_1817           |            |                            |
|                | DP_OP_1193J1_124_1817 |     |                            |
| DP_OP_1194J1_125_2215           |            |                            |
|                | DP_OP_1194J1_125_2215 |     |                            |
| DP_OP_1195J1_126_1817           |            |                            |
|                | DP_OP_1195J1_126_1817 |     |                            |
| DP_OP_1196J1_127_2215           |            |                            |
|                | DP_OP_1196J1_127_2215 |     |                            |
| DP_OP_1197J1_128_1817           |            |                            |
|                | DP_OP_1197J1_128_1817 |     |                            |
| DP_OP_1198J1_129_2215           |            |                            |
|                | DP_OP_1198J1_129_2215 |     |                            |
| DP_OP_1199J1_130_2215           |            |                            |
|                | DP_OP_1199J1_130_2215 |     |                            |
| DP_OP_1200J1_131_2215           |            |                            |
|                | DP_OP_1200J1_131_2215 |     |                            |
| DP_OP_1201J1_132_2215           |            |                            |
|                | DP_OP_1201J1_132_2215 |     |                            |
| DP_OP_1202J1_133_9291           |            |                            |
|                | DP_OP_1202J1_133_9291 |     |                            |
| DP_OP_1203J1_134_2215           |            |                            |
|                | DP_OP_1203J1_134_2215 |     |                            |
| DP_OP_1204J1_135_2215           |            |                            |
|                | DP_OP_1204J1_135_2215 |     |                            |
| DP_OP_1205J1_136_2215           |            |                            |
|                | DP_OP_1205J1_136_2215 |     |                            |
| DP_OP_1206J1_137_2215           |            |                            |
|                | DP_OP_1206J1_137_2215 |     |                            |
| DP_OP_1207J1_138_2215           |            |                            |
|                | DP_OP_1207J1_138_2215 |     |                            |
| DP_OP_1208J1_139_2215           |            |                            |
|                | DP_OP_1208J1_139_2215 |     |                            |
| DP_OP_1209J1_140_2215           |            |                            |
|                | DP_OP_1209J1_140_2215 |     |                            |
| DP_OP_1210J1_141_2215           |            |                            |
|                | DP_OP_1210J1_141_2215 |     |                            |
| DP_OP_1211J1_142_2215           |            |                            |
|                | DP_OP_1211J1_142_2215 |     |                            |
| DP_OP_1212J1_143_9291           |            |                            |
|                | DP_OP_1212J1_143_9291 |     |                            |
| DP_OP_1213J1_144_9291           |            |                            |
|                | DP_OP_1213J1_144_9291 |     |                            |
| DP_OP_1214J1_145_9291           |            |                            |
|                | DP_OP_1214J1_145_9291 |     |                            |
| DP_OP_1215J1_146_9291           |            |                            |
|                | DP_OP_1215J1_146_9291 |     |                            |
| DP_OP_1216J1_147_9291           |            |                            |
|                | DP_OP_1216J1_147_9291 |     |                            |
| DP_OP_1217J1_148_9291           |            |                            |
|                | DP_OP_1217J1_148_9291 |     |                            |
| DP_OP_1218J1_149_9291           |            |                            |
|                | DP_OP_1218J1_149_9291 |     |                            |
| DP_OP_1219J1_150_8957           |            |                            |
|                | DP_OP_1219J1_150_8957 |     |                            |
| DP_OP_1220J1_151_3138           |            |                            |
|                | DP_OP_1220J1_151_3138 |     |                            |
| DP_OP_1221J1_152_4634           |            |                            |
|                | DP_OP_1221J1_152_4634 |     |                            |
=============================================================================

Datapath Report for DP_OP_1191J1_122_1817
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1191J1_122_1817 | pack7/add_661 (MPCA.v:661)                         |
|                      | pack7/add_661_2 (MPCA.v:661)                        |
|                      | pack7/add_661_3 (MPCA.v:661)                        |
|                      | packetsort/COM_4/gt_851 (MPCA.v:851)                |
|                      | pack6/add_661 (MPCA.v:661)                          |
|                      | pack6/add_661_2 (MPCA.v:661)                        |
|                      | pack6/add_661_3 (MPCA.v:661)                        |
|                      | packetsort/COM_4/lt_855 (MPCA.v:855)                |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 5     |                                          |
| I2    | PI   | Signed   | 5     |                                          |
| I3    | PI   | Signed   | 7     |                                          |
| I4    | PI   | Signed   | 5     |                                          |
| I5    | PI   | Signed   | 5     |                                          |
| I6    | PI   | Signed   | 5     |                                          |
| I7    | PI   | Signed   | 7     |                                          |
| I8    | PI   | Signed   | 5     |                                          |
| O1    | PO   | Signed   | 8     | I1 + I2 + I3 + I4 (MPCA.v:661)           |
| O2    | PO   | Signed   | 1     | O3 > O1 (MPCA.v:851)                     |
| O3    | PO   | Signed   | 8     | I5 + I6 + I7 + I8 (MPCA.v:661)           |
| O4    | PO   | Signed   | 1     | O3 < O1 (MPCA.v:855)                     |
==============================================================================

Datapath Report for DP_OP_1192J1_123_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1192J1_123_2215 | D76/add_531 (MPCA.v:531) D76/add_531_2 (MPCA.v:531) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:531)   |
==============================================================================

Datapath Report for DP_OP_1193J1_124_1817
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1193J1_124_1817 | pack3/add_661 (MPCA.v:661)                         |
|                      | pack3/add_661_2 (MPCA.v:661)                        |
|                      | pack3/add_661_3 (MPCA.v:661)                        |
|                      | packetsort/COM_2/gt_851 (MPCA.v:851)                |
|                      | pack2/add_661 (MPCA.v:661)                          |
|                      | pack2/add_661_2 (MPCA.v:661)                        |
|                      | pack2/add_661_3 (MPCA.v:661)                        |
|                      | packetsort/COM_2/lt_855 (MPCA.v:855)                |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 5     |                                          |
| I2    | PI   | Signed   | 5     |                                          |
| I3    | PI   | Signed   | 7     |                                          |
| I4    | PI   | Signed   | 5     |                                          |
| I5    | PI   | Signed   | 5     |                                          |
| I6    | PI   | Signed   | 5     |                                          |
| I7    | PI   | Signed   | 7     |                                          |
| I8    | PI   | Signed   | 5     |                                          |
| O1    | PO   | Signed   | 8     | I1 + I2 + I3 + I4 (MPCA.v:661)           |
| O2    | PO   | Signed   | 1     | O3 > O1 (MPCA.v:851)                     |
| O3    | PO   | Signed   | 8     | I5 + I6 + I7 + I8 (MPCA.v:661)           |
| O4    | PO   | Signed   | 1     | O3 < O1 (MPCA.v:855)                     |
==============================================================================

Datapath Report for DP_OP_1194J1_125_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1194J1_125_2215 | D32/add_531 (MPCA.v:531) D32/add_531_2 (MPCA.v:531) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:531)   |
==============================================================================

Datapath Report for DP_OP_1195J1_126_1817
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1195J1_126_1817 | pack5/add_661 (MPCA.v:661)                         |
|                      | pack5/add_661_2 (MPCA.v:661)                        |
|                      | pack5/add_661_3 (MPCA.v:661)                        |
|                      | packetsort/COM_3/gt_851 (MPCA.v:851)                |
|                      | pack4/add_661 (MPCA.v:661)                          |
|                      | pack4/add_661_2 (MPCA.v:661)                        |
|                      | pack4/add_661_3 (MPCA.v:661)                        |
|                      | packetsort/COM_3/lt_855 (MPCA.v:855)                |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 5     |                                          |
| I2    | PI   | Signed   | 5     |                                          |
| I3    | PI   | Signed   | 7     |                                          |
| I4    | PI   | Signed   | 5     |                                          |
| I5    | PI   | Signed   | 5     |                                          |
| I6    | PI   | Signed   | 5     |                                          |
| I7    | PI   | Signed   | 7     |                                          |
| I8    | PI   | Signed   | 5     |                                          |
| O1    | PO   | Signed   | 8     | I1 + I2 + I3 + I4 (MPCA.v:661)           |
| O2    | PO   | Signed   | 1     | O3 > O1 (MPCA.v:851)                     |
| O3    | PO   | Signed   | 8     | I5 + I6 + I7 + I8 (MPCA.v:661)           |
| O4    | PO   | Signed   | 1     | O3 < O1 (MPCA.v:855)                     |
==============================================================================

Datapath Report for DP_OP_1196J1_127_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1196J1_127_2215 | D54/add_531 (MPCA.v:531) D54/add_531_2 (MPCA.v:531) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:531)   |
==============================================================================

Datapath Report for DP_OP_1197J1_128_1817
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1197J1_128_1817 | pack1/add_661 (MPCA.v:661)                         |
|                      | pack1/add_661_2 (MPCA.v:661)                        |
|                      | pack1/add_661_3 (MPCA.v:661)                        |
|                      | packetsort/COM_1/gt_851 (MPCA.v:851)                |
|                      | pack0/add_661 (MPCA.v:661)                          |
|                      | pack0/add_661_2 (MPCA.v:661)                        |
|                      | pack0/add_661_3 (MPCA.v:661)                        |
|                      | packetsort/COM_1/lt_855 (MPCA.v:855)                |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 5     |                                          |
| I2    | PI   | Signed   | 5     |                                          |
| I3    | PI   | Signed   | 7     |                                          |
| I4    | PI   | Signed   | 5     |                                          |
| I5    | PI   | Signed   | 5     |                                          |
| I6    | PI   | Signed   | 5     |                                          |
| I7    | PI   | Signed   | 7     |                                          |
| I8    | PI   | Signed   | 5     |                                          |
| O1    | PO   | Signed   | 8     | I1 + I2 + I3 + I4 (MPCA.v:661)           |
| O2    | PO   | Signed   | 1     | O3 > O1 (MPCA.v:851)                     |
| O3    | PO   | Signed   | 8     | I5 + I6 + I7 + I8 (MPCA.v:661)           |
| O4    | PO   | Signed   | 1     | O3 < O1 (MPCA.v:855)                     |
==============================================================================

Datapath Report for DP_OP_1198J1_129_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1198J1_129_2215 | D10/add_531 (MPCA.v:531) D10/add_531_2 (MPCA.v:531) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:531)   |
==============================================================================

Datapath Report for DP_OP_1199J1_130_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1199J1_130_2215 | D76/add_528 (MPCA.v:528) D76/add_528_2 (MPCA.v:528) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:528)   |
==============================================================================

Datapath Report for DP_OP_1200J1_131_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1200J1_131_2215 | D76/add_529 (MPCA.v:529) D76/add_529_2 (MPCA.v:529) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:529)   |
==============================================================================

Datapath Report for DP_OP_1201J1_132_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1201J1_132_2215 | D76/add_530 (MPCA.v:530) D76/add_530_2 (MPCA.v:530) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:530)   |
==============================================================================

Datapath Report for DP_OP_1202J1_133_9291
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1202J1_133_9291 | maskpack0/add_690 (MPCA.v:690)                     |
|                      | maskpack0/add_690_2 (MPCA.v:690)                    |
|                      | maskpack0/add_690_3 (MPCA.v:690)                    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 3     |                                          |
| I2    | PI   | Unsigned | 2     |                                          |
| I3    | PI   | Unsigned | 3     |                                          |
| I4    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + I2 + I3 + I4 (MPCA.v:690)           |
==============================================================================

Datapath Report for DP_OP_1203J1_134_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1203J1_134_2215 | D10/add_528 (MPCA.v:528) D10/add_528_2 (MPCA.v:528) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:528)   |
==============================================================================

Datapath Report for DP_OP_1204J1_135_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1204J1_135_2215 | D10/add_529 (MPCA.v:529) D10/add_529_2 (MPCA.v:529) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:529)   |
==============================================================================

Datapath Report for DP_OP_1205J1_136_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1205J1_136_2215 | D10/add_530 (MPCA.v:530) D10/add_530_2 (MPCA.v:530) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:530)   |
==============================================================================

Datapath Report for DP_OP_1206J1_137_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1206J1_137_2215 | D32/add_528 (MPCA.v:528) D32/add_528_2 (MPCA.v:528) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:528)   |
==============================================================================

Datapath Report for DP_OP_1207J1_138_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1207J1_138_2215 | D32/add_529 (MPCA.v:529) D32/add_529_2 (MPCA.v:529) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:529)   |
==============================================================================

Datapath Report for DP_OP_1208J1_139_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1208J1_139_2215 | D32/add_530 (MPCA.v:530) D32/add_530_2 (MPCA.v:530) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:530)   |
==============================================================================

Datapath Report for DP_OP_1209J1_140_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1209J1_140_2215 | D54/add_528 (MPCA.v:528) D54/add_528_2 (MPCA.v:528) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:528)   |
==============================================================================

Datapath Report for DP_OP_1210J1_141_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1210J1_141_2215 | D54/add_529 (MPCA.v:529) D54/add_529_2 (MPCA.v:529) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:529)   |
==============================================================================

Datapath Report for DP_OP_1211J1_142_2215
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1211J1_142_2215 | D54/add_530 (MPCA.v:530) D54/add_530_2 (MPCA.v:530) |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 16    |                                          |
| I2    | PI   | Unsigned | 16    |                                          |
| O1    | PO   | Unsigned | 16    | I1 + $unsigned(1'b1) + I2 (MPCA.v:530)   |
==============================================================================

Datapath Report for DP_OP_1212J1_143_9291
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1212J1_143_9291 | maskpack7/add_690 (MPCA.v:690)                     |
|                      | maskpack7/add_690_2 (MPCA.v:690)                    |
|                      | maskpack7/add_690_3 (MPCA.v:690)                    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 3     |                                          |
| I2    | PI   | Unsigned | 2     |                                          |
| I3    | PI   | Unsigned | 3     |                                          |
| I4    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + I2 + I3 + I4 (MPCA.v:690)           |
==============================================================================

Datapath Report for DP_OP_1213J1_144_9291
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1213J1_144_9291 | maskpack6/add_690 (MPCA.v:690)                     |
|                      | maskpack6/add_690_2 (MPCA.v:690)                    |
|                      | maskpack6/add_690_3 (MPCA.v:690)                    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 3     |                                          |
| I2    | PI   | Unsigned | 2     |                                          |
| I3    | PI   | Unsigned | 3     |                                          |
| I4    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + I2 + I3 + I4 (MPCA.v:690)           |
==============================================================================

Datapath Report for DP_OP_1214J1_145_9291
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1214J1_145_9291 | maskpack5/add_690 (MPCA.v:690)                     |
|                      | maskpack5/add_690_2 (MPCA.v:690)                    |
|                      | maskpack5/add_690_3 (MPCA.v:690)                    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 3     |                                          |
| I2    | PI   | Unsigned | 2     |                                          |
| I3    | PI   | Unsigned | 3     |                                          |
| I4    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + I2 + I3 + I4 (MPCA.v:690)           |
==============================================================================

Datapath Report for DP_OP_1215J1_146_9291
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1215J1_146_9291 | maskpack4/add_690 (MPCA.v:690)                     |
|                      | maskpack4/add_690_2 (MPCA.v:690)                    |
|                      | maskpack4/add_690_3 (MPCA.v:690)                    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 3     |                                          |
| I2    | PI   | Unsigned | 2     |                                          |
| I3    | PI   | Unsigned | 3     |                                          |
| I4    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + I2 + I3 + I4 (MPCA.v:690)           |
==============================================================================

Datapath Report for DP_OP_1216J1_147_9291
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1216J1_147_9291 | maskpack3/add_690 (MPCA.v:690)                     |
|                      | maskpack3/add_690_2 (MPCA.v:690)                    |
|                      | maskpack3/add_690_3 (MPCA.v:690)                    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 3     |                                          |
| I2    | PI   | Unsigned | 2     |                                          |
| I3    | PI   | Unsigned | 3     |                                          |
| I4    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + I2 + I3 + I4 (MPCA.v:690)           |
==============================================================================

Datapath Report for DP_OP_1217J1_148_9291
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1217J1_148_9291 | maskpack2/add_690 (MPCA.v:690)                     |
|                      | maskpack2/add_690_2 (MPCA.v:690)                    |
|                      | maskpack2/add_690_3 (MPCA.v:690)                    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 3     |                                          |
| I2    | PI   | Unsigned | 2     |                                          |
| I3    | PI   | Unsigned | 3     |                                          |
| I4    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + I2 + I3 + I4 (MPCA.v:690)           |
==============================================================================

Datapath Report for DP_OP_1218J1_149_9291
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1218J1_149_9291 | maskpack1/add_690 (MPCA.v:690)                     |
|                      | maskpack1/add_690_2 (MPCA.v:690)                    |
|                      | maskpack1/add_690_3 (MPCA.v:690)                    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 3     |                                          |
| I2    | PI   | Unsigned | 2     |                                          |
| I3    | PI   | Unsigned | 3     |                                          |
| I4    | PI   | Unsigned | 4     |                                          |
| O1    | PO   | Unsigned | 5     | I1 + I2 + I3 + I4 (MPCA.v:690)           |
==============================================================================

Datapath Report for DP_OP_1219J1_150_8957
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1219J1_150_8957 | gt_311_2 (MPCA.v:311) gt_312 (MPCA.v:312)          |
|                      | add_264 (MPCA.v:264) gte_269 (MPCA.v:269)           |
|                      | gte_270 (MPCA.v:270) eq_285 (MPCA.v:285)            |
|                      | eq_285_2 (MPCA.v:285)                               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| I2    | PI   | Unsigned | 3     |                                          |
| I3    | PI   | Unsigned | 5     |                                          |
| I4    | PI   | Unsigned | 5     |                                          |
| T0    | IFO  | Unsigned | 5     | I1 + I2 (MPCA.v:264)                     |
| O1    | PO   | Unsigned | 1     | T0 > $unsigned(4'b1110) ( MPCA.v:311 MPCA.v:312 ) |
| O2    | PO   | Unsigned | 1     | T0 >= I3 (MPCA.v:269)                    |
| O3    | PO   | Unsigned | 1     | T0 >= I4 (MPCA.v:270)                    |
| O4    | PO   | Unsigned | 1     | I3 == T0 (MPCA.v:285)                    |
| O5    | PO   | Unsigned | 1     | T0 == I4 (MPCA.v:285)                    |
==============================================================================

Note: DP_OP_1219J1_150_8957 was from data path split due to depth control


Datapath Report for DP_OP_1220J1_151_3138
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1220J1_151_3138 | gt_310 (MPCA.v:310) gt_312_2 (MPCA.v:312)          |
|                      | add_265 (MPCA.v:265) gte_277 (MPCA.v:277)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| I2    | PI   | Unsigned | 3     |                                          |
| I3    | PI   | Unsigned | 5     |                                          |
| O1    | PO   | Unsigned | 1     | O2 > $unsigned(4'b1110) ( MPCA.v:310 MPCA.v:312 ) |
| O2    | PO   | Unsigned | 5     | I1 + I2 (MPCA.v:265)                     |
| O3    | PO   | Unsigned | 1     | O2 >= I3 (MPCA.v:277)                    |
==============================================================================

Note: DP_OP_1220J1_151_3138 was from data path split due to depth control


Datapath Report for DP_OP_1221J1_152_4634
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1221J1_152_4634 | gt_310_2 (MPCA.v:310) gt_311 (MPCA.v:311)          |
|                      | add_266 (MPCA.v:266)                                |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 4     |                                          |
| I2    | PI   | Unsigned | 3     |                                          |
| O1    | PO   | Unsigned | 1     | O2 > $unsigned(4'b1110) ( MPCA.v:310 MPCA.v:311 ) |
| O2    | PO   | Unsigned | 5     | I1 + I2 (MPCA.v:266)                     |
==============================================================================

Note: DP_OP_1221J1_152_4634 was from data path split due to depth control



Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| eq_x_2             | DW_cmp           | apparch (area)     |                |
| eq_x_3             | DW_cmp           | apparch (area)     |                |
| eq_x_4             | DW_cmp           | apparch (area)     |                |
| eq_x_5             | DW_cmp           | apparch (area)     |                |
| eq_x_6             | DW_cmp           | apparch (area)     |                |
| eq_x_7             | DW_cmp           | apparch (area)     |                |
| eq_x_8             | DW_cmp           | apparch (area)     |                |
| eq_x_9             | DW_cmp           | apparch (area)     |                |
| add_x_101          | DW01_add         | pparch (speed)     |                |
| gt_x_115           | DW_cmp           | apparch (area)     |                |
| add_x_124          | DW01_inc         | apparch (area)     |                |
| lte_x_128          | DW_cmp           | apparch (area)     |                |
| lte_x_129          | DW_cmp           | apparch (area)     |                |
| eq_x_130           | DW_cmp           | apparch (area)     |                |
| lte_x_131          | DW_cmp           | apparch (area)     |                |
| eq_x_132           | DW_cmp           | apparch (area)     |                |
| lte_x_133          | DW_cmp           | apparch (area)     |                |
| eq_x_134           | DW_cmp           | apparch (area)     |                |
| add_x_161          | DW01_add         | pparch (speed)     |                |
| add_x_162          | DW01_add         | pparch (speed)     |                |
| add_x_163          | DW01_add         | pparch (speed)     |                |
| gt_x_265           | DW_cmp           | apparch (area)     |                |
| gt_x_269           | DW_cmp           | apparch (area)     |                |
| gt_x_273           | DW_cmp           | apparch (area)     |                |
| gt_x_279           | DW_cmp           | apparch (area)     |                |
| gt_x_285           | DW_cmp           | apparch (area)     |                |
| gt_x_289           | DW_cmp           | apparch (area)     |                |
| gt_x_293           | DW_cmp           | apparch (area)     |                |
| add_x_296          | DW01_inc         | apparch (area)     |                |
| add_x_297          | DW01_inc         | apparch (area)     |                |
| add_x_298          | DW01_inc         | apparch (area)     |                |
| lte_x_308          | DW_cmp           | apparch (area)     |                |
| lte_x_309          | DW_cmp           | apparch (area)     |                |
| eq_x_310           | DW_cmp           | apparch (area)     |                |
| lte_x_311          | DW_cmp           | apparch (area)     |                |
| eq_x_312           | DW_cmp           | apparch (area)     |                |
| lte_x_313          | DW_cmp           | apparch (area)     |                |
| eq_x_314           | DW_cmp           | apparch (area)     |                |
| add_x_347          | DW01_inc         | apparch (area)     |                |
| add_x_348          | DW01_inc         | apparch (area)     |                |
| add_x_349          | DW01_inc         | apparch (area)     |                |
| add_x_356          | DW01_inc         | apparch (area)     |                |
| lte_x_361          | DW_cmp           | apparch (area)     |                |
| lte_x_362          | DW_cmp           | apparch (area)     |                |
| eq_x_363           | DW_cmp           | apparch (area)     |                |
| lte_x_364          | DW_cmp           | apparch (area)     |                |
| eq_x_365           | DW_cmp           | apparch (area)     |                |
| lte_x_366          | DW_cmp           | apparch (area)     |                |
| eq_x_367           | DW_cmp           | apparch (area)     |                |
| add_x_396          | DW01_inc         | apparch (area)     |                |
| add_x_397          | DW01_inc         | apparch (area)     |                |
| add_x_398          | DW01_inc         | apparch (area)     |                |
| add_x_405          | DW01_inc         | apparch (area)     |                |
| lte_x_409          | DW_cmp           | apparch (area)     |                |
| lte_x_410          | DW_cmp           | apparch (area)     |                |
| eq_x_411           | DW_cmp           | apparch (area)     |                |
| lte_x_412          | DW_cmp           | apparch (area)     |                |
| eq_x_413           | DW_cmp           | apparch (area)     |                |
| lte_x_414          | DW_cmp           | apparch (area)     |                |
| eq_x_415           | DW_cmp           | apparch (area)     |                |
| add_x_444          | DW01_inc         | apparch (area)     |                |
| add_x_445          | DW01_inc         | apparch (area)     |                |
| add_x_446          | DW01_inc         | apparch (area)     |                |
| add_x_453          | DW01_inc         | apparch (area)     |                |
| lte_x_457          | DW_cmp           | apparch (area)     |                |
| lte_x_458          | DW_cmp           | apparch (area)     |                |
| eq_x_459           | DW_cmp           | apparch (area)     |                |
| lte_x_460          | DW_cmp           | apparch (area)     |                |
| eq_x_461           | DW_cmp           | apparch (area)     |                |
| lte_x_462          | DW_cmp           | apparch (area)     |                |
| eq_x_463           | DW_cmp           | apparch (area)     |                |
| add_x_506          | DW01_inc         | apparch (area)     |                |
| add_x_507          | DW01_inc         | apparch (area)     |                |
| add_x_508          | DW01_inc         | apparch (area)     |                |
| add_x_515          | DW01_inc         | apparch (area)     |                |
| lte_x_519          | DW_cmp           | apparch (area)     |                |
| lte_x_520          | DW_cmp           | apparch (area)     |                |
| eq_x_521           | DW_cmp           | apparch (area)     |                |
| lte_x_522          | DW_cmp           | apparch (area)     |                |
| eq_x_523           | DW_cmp           | apparch (area)     |                |
| lte_x_524          | DW_cmp           | apparch (area)     |                |
| eq_x_525           | DW_cmp           | apparch (area)     |                |
| add_x_554          | DW01_inc         | apparch (area)     |                |
| add_x_555          | DW01_inc         | apparch (area)     |                |
| add_x_556          | DW01_inc         | apparch (area)     |                |
| add_x_567          | DW01_inc         | apparch (area)     |                |
| lte_x_572          | DW_cmp           | apparch (area)     |                |
| lte_x_573          | DW_cmp           | apparch (area)     |                |
| eq_x_574           | DW_cmp           | apparch (area)     |                |
| lte_x_575          | DW_cmp           | apparch (area)     |                |
| eq_x_576           | DW_cmp           | apparch (area)     |                |
| lte_x_577          | DW_cmp           | apparch (area)     |                |
| eq_x_578           | DW_cmp           | apparch (area)     |                |
| add_x_613          | DW01_inc         | apparch (area)     |                |
| add_x_614          | DW01_inc         | apparch (area)     |                |
| add_x_615          | DW01_inc         | apparch (area)     |                |
| add_x_622          | DW01_inc         | apparch (area)     |                |
| lte_x_626          | DW_cmp           | apparch (area)     |                |
| lte_x_627          | DW_cmp           | apparch (area)     |                |
| eq_x_628           | DW_cmp           | apparch (area)     |                |
| lte_x_629          | DW_cmp           | apparch (area)     |                |
| eq_x_630           | DW_cmp           | apparch (area)     |                |
| lte_x_631          | DW_cmp           | apparch (area)     |                |
| eq_x_632           | DW_cmp           | apparch (area)     |                |
| gt_x_665           | DW_cmp           | apparch (area)     |                |
| lt_x_666           | DW_cmp           | apparch (area)     |                |
| lt_x_667           | DW_cmp           | apparch (area)     |                |
| gt_x_670           | DW_cmp           | apparch (area)     |                |
| lt_x_671           | DW_cmp           | apparch (area)     |                |
| lt_x_672           | DW_cmp           | apparch (area)     |                |
| gt_x_677           | DW_cmp           | apparch (area)     |                |
| lt_x_678           | DW_cmp           | apparch (area)     |                |
| lt_x_679           | DW_cmp           | apparch (area)     |                |
| gt_x_683           | DW_cmp           | apparch (area)     |                |
| lt_x_684           | DW_cmp           | apparch (area)     |                |
| lt_x_685           | DW_cmp           | apparch (area)     |                |
| gt_x_690           | DW_cmp           | apparch (area)     |                |
| lt_x_691           | DW_cmp           | apparch (area)     |                |
| lt_x_692           | DW_cmp           | apparch (area)     |                |
| gt_x_695           | DW_cmp           | apparch (area)     |                |
| lt_x_696           | DW_cmp           | apparch (area)     |                |
| lt_x_697           | DW_cmp           | apparch (area)     |                |
| gt_x_700           | DW_cmp           | apparch (area)     |                |
| lt_x_701           | DW_cmp           | apparch (area)     |                |
| lt_x_702           | DW_cmp           | apparch (area)     |                |
| gt_x_705           | DW_cmp           | apparch (area)     |                |
| lt_x_706           | DW_cmp           | apparch (area)     |                |
| lt_x_707           | DW_cmp           | apparch (area)     |                |
| gt_x_710           | DW_cmp           | apparch (area)     |                |
| lt_x_711           | DW_cmp           | apparch (area)     |                |
| lt_x_712           | DW_cmp           | apparch (area)     |                |
| gt_x_715           | DW_cmp           | apparch (area)     |                |
| lt_x_716           | DW_cmp           | apparch (area)     |                |
| lt_x_717           | DW_cmp           | apparch (area)     |                |
| gt_x_720           | DW_cmp           | apparch (area)     |                |
| lt_x_721           | DW_cmp           | apparch (area)     |                |
| lt_x_722           | DW_cmp           | apparch (area)     |                |
| gt_x_725           | DW_cmp           | apparch (area)     |                |
| lt_x_726           | DW_cmp           | apparch (area)     |                |
| lt_x_727           | DW_cmp           | apparch (area)     |                |
| gt_x_730           | DW_cmp           | apparch (area)     |                |
| lt_x_731           | DW_cmp           | apparch (area)     |                |
| lt_x_732           | DW_cmp           | apparch (area)     |                |
| gt_x_741           | DW_cmp           | apparch (area)     |                |
| lt_x_742           | DW_cmp           | apparch (area)     |                |
| lt_x_743           | DW_cmp           | apparch (area)     |                |
| gt_x_746           | DW_cmp           | apparch (area)     |                |
| lt_x_747           | DW_cmp           | apparch (area)     |                |
| lt_x_748           | DW_cmp           | apparch (area)     |                |
| add_x_99           | DW01_add         | pparch (speed)     |                |
| add_x_100          | DW01_add         | pparch (speed)     |                |
| DP_OP_1191J1_122_1817                 |                    |                |
|                    | DP_OP_1191J1_122_1817 | str (area,speed)               |
| DP_OP_1192J1_123_2215                 |                    |                |
|                    | DP_OP_1192J1_123_2215 | str (speed)   |                |
| DP_OP_1193J1_124_1817                 |                    |                |
|                    | DP_OP_1193J1_124_1817 | str (area,speed)               |
| DP_OP_1194J1_125_2215                 |                    |                |
|                    | DP_OP_1194J1_125_2215 | str (speed)   |                |
| DP_OP_1195J1_126_1817                 |                    |                |
|                    | DP_OP_1195J1_126_1817 | str (area,speed)               |
| DP_OP_1196J1_127_2215                 |                    |                |
|                    | DP_OP_1196J1_127_2215 | str (speed)   |                |
| DP_OP_1197J1_128_1817                 |                    |                |
|                    | DP_OP_1197J1_128_1817 | str (area,speed)               |
| DP_OP_1198J1_129_2215                 |                    |                |
|                    | DP_OP_1198J1_129_2215 | str (speed)   |                |
| DP_OP_1199J1_130_2215                 |                    |                |
|                    | DP_OP_1199J1_130_2215 | str (area,speed)               |
| DP_OP_1200J1_131_2215                 |                    |                |
|                    | DP_OP_1200J1_131_2215 | str (area,speed)               |
| DP_OP_1201J1_132_2215                 |                    |                |
|                    | DP_OP_1201J1_132_2215 | str (area,speed)               |
| DP_OP_1202J1_133_9291                 |                    |                |
|                    | DP_OP_1202J1_133_9291 | str (area)    |                |
| DP_OP_1203J1_134_2215                 |                    |                |
|                    | DP_OP_1203J1_134_2215 | str (area,speed)               |
| DP_OP_1204J1_135_2215                 |                    |                |
|                    | DP_OP_1204J1_135_2215 | str (area,speed)               |
| DP_OP_1205J1_136_2215                 |                    |                |
|                    | DP_OP_1205J1_136_2215 | str (area,speed)               |
| DP_OP_1206J1_137_2215                 |                    |                |
|                    | DP_OP_1206J1_137_2215 | str (area,speed)               |
| DP_OP_1207J1_138_2215                 |                    |                |
|                    | DP_OP_1207J1_138_2215 | str (area,speed)               |
| DP_OP_1208J1_139_2215                 |                    |                |
|                    | DP_OP_1208J1_139_2215 | str (area,speed)               |
| DP_OP_1209J1_140_2215                 |                    |                |
|                    | DP_OP_1209J1_140_2215 | str (area,speed)               |
| DP_OP_1210J1_141_2215                 |                    |                |
|                    | DP_OP_1210J1_141_2215 | str (area,speed)               |
| DP_OP_1211J1_142_2215                 |                    |                |
|                    | DP_OP_1211J1_142_2215 | str (area,speed)               |
| DP_OP_1212J1_143_9291                 |                    |                |
|                    | DP_OP_1212J1_143_9291 | str (area)    |                |
| DP_OP_1213J1_144_9291                 |                    |                |
|                    | DP_OP_1213J1_144_9291 | str (area)    |                |
| DP_OP_1214J1_145_9291                 |                    |                |
|                    | DP_OP_1214J1_145_9291 | str (area)    |                |
| DP_OP_1215J1_146_9291                 |                    |                |
|                    | DP_OP_1215J1_146_9291 | str (area)    |                |
| DP_OP_1216J1_147_9291                 |                    |                |
|                    | DP_OP_1216J1_147_9291 | str (area)    |                |
| DP_OP_1217J1_148_9291                 |                    |                |
|                    | DP_OP_1217J1_148_9291 | str (area)    |                |
| DP_OP_1218J1_149_9291                 |                    |                |
|                    | DP_OP_1218J1_149_9291 | str (area)    |                |
| DP_OP_1219J1_150_8957                 |                    |                |
|                    | DP_OP_1219J1_150_8957 | str (area,speed)               |
| DP_OP_1220J1_151_3138                 |                    |                |
|                    | DP_OP_1220J1_151_3138 | str (speed)   |                |
| DP_OP_1221J1_152_4634                 |                    |                |
|                    | DP_OP_1221J1_152_4634 | str (area)    |                |
===============================================================================

1
