 
****************************************
Report : resources
Design : SUDOKU
Version: T-2022.03
Date   : Mon Sep 22 02:56:51 2025
****************************************


Resource Report for this hierarchy in file ../01_RTL/SUDOKU.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gt_x_1         | DW_cmp         | width=7    | gt_76 (SUDOKU.v:76)        |
| div_3          | DW_div_uns     | a_width=7  | div_95 (SUDOKU.v:95)       |
|                |                | b_width=4  |                            |
| rem_4          | DW_div_uns     | a_width=7  | rem_95 (SUDOKU.v:95)       |
|                |                | b_width=4  |                            |
| add_x_6        | DW01_inc       | width=7    | add_104_S2 (SUDOKU.v:104)  |
| sub_x_8        | DW01_dec       | width=9    | sub_129 (SUDOKU.v:129)     |
| sub_x_9        | DW01_dec       | width=9    | sub_129_G2 (SUDOKU.v:129)  |
| sub_x_10       | DW01_dec       | width=9    | sub_129_G3 (SUDOKU.v:129)  |
| sub_x_11       | DW01_dec       | width=9    | sub_129_G4 (SUDOKU.v:129)  |
| sub_x_12       | DW01_dec       | width=9    | sub_129_G5 (SUDOKU.v:129)  |
| sub_x_13       | DW01_dec       | width=9    | sub_129_G6 (SUDOKU.v:129)  |
| sub_x_14       | DW01_dec       | width=9    | sub_129_G7 (SUDOKU.v:129)  |
| sub_x_15       | DW01_dec       | width=9    | sub_129_G8 (SUDOKU.v:129)  |
| sub_x_16       | DW01_dec       | width=9    | sub_129_G9 (SUDOKU.v:129)  |
| sub_x_17       | DW01_dec       | width=9    | sub_129_G10 (SUDOKU.v:129) |
| sub_x_18       | DW01_dec       | width=9    | sub_129_G11 (SUDOKU.v:129) |
| sub_x_19       | DW01_dec       | width=9    | sub_129_G12 (SUDOKU.v:129) |
| sub_x_20       | DW01_dec       | width=9    | sub_129_G13 (SUDOKU.v:129) |
| sub_x_21       | DW01_dec       | width=9    | sub_129_G14 (SUDOKU.v:129) |
| sub_x_22       | DW01_dec       | width=9    | sub_129_G15 (SUDOKU.v:129) |
| sub_x_23       | DW01_dec       | width=9    | sub_129_G16 (SUDOKU.v:129) |
| sub_x_24       | DW01_dec       | width=9    | sub_129_G17 (SUDOKU.v:129) |
| sub_x_25       | DW01_dec       | width=9    | sub_129_G18 (SUDOKU.v:129) |
| sub_x_26       | DW01_dec       | width=9    | sub_129_G19 (SUDOKU.v:129) |
| sub_x_27       | DW01_dec       | width=9    | sub_129_G20 (SUDOKU.v:129) |
| sub_x_28       | DW01_dec       | width=9    | sub_129_G21 (SUDOKU.v:129) |
| sub_x_29       | DW01_dec       | width=9    | sub_129_G22 (SUDOKU.v:129) |
| sub_x_30       | DW01_dec       | width=9    | sub_129_G23 (SUDOKU.v:129) |
| sub_x_31       | DW01_dec       | width=9    | sub_129_G24 (SUDOKU.v:129) |
| sub_x_32       | DW01_dec       | width=9    | sub_129_G25 (SUDOKU.v:129) |
| sub_x_33       | DW01_dec       | width=9    | sub_129_G26 (SUDOKU.v:129) |
| sub_x_34       | DW01_dec       | width=9    | sub_129_G27 (SUDOKU.v:129) |
| sub_x_35       | DW01_dec       | width=9    | sub_129_G28 (SUDOKU.v:129) |
| sub_x_36       | DW01_dec       | width=9    | sub_129_G29 (SUDOKU.v:129) |
| sub_x_37       | DW01_dec       | width=9    | sub_129_G30 (SUDOKU.v:129) |
| sub_x_38       | DW01_dec       | width=9    | sub_129_G31 (SUDOKU.v:129) |
| sub_x_39       | DW01_dec       | width=9    | sub_129_G32 (SUDOKU.v:129) |
| sub_x_40       | DW01_dec       | width=9    | sub_129_G33 (SUDOKU.v:129) |
| sub_x_41       | DW01_dec       | width=9    | sub_129_G34 (SUDOKU.v:129) |
| sub_x_42       | DW01_dec       | width=9    | sub_129_G35 (SUDOKU.v:129) |
| sub_x_43       | DW01_dec       | width=9    | sub_129_G36 (SUDOKU.v:129) |
| sub_x_44       | DW01_dec       | width=9    | sub_129_G37 (SUDOKU.v:129) |
| sub_x_45       | DW01_dec       | width=9    | sub_129_G38 (SUDOKU.v:129) |
| sub_x_46       | DW01_dec       | width=9    | sub_129_G39 (SUDOKU.v:129) |
| sub_x_47       | DW01_dec       | width=9    | sub_129_G40 (SUDOKU.v:129) |
| sub_x_48       | DW01_dec       | width=9    | sub_129_G41 (SUDOKU.v:129) |
| sub_x_49       | DW01_dec       | width=9    | sub_129_G42 (SUDOKU.v:129) |
| sub_x_50       | DW01_dec       | width=9    | sub_129_G43 (SUDOKU.v:129) |
| sub_x_51       | DW01_dec       | width=9    | sub_129_G44 (SUDOKU.v:129) |
| sub_x_52       | DW01_dec       | width=9    | sub_129_G45 (SUDOKU.v:129) |
| sub_x_53       | DW01_dec       | width=9    | sub_129_G46 (SUDOKU.v:129) |
| sub_x_54       | DW01_dec       | width=9    | sub_129_G47 (SUDOKU.v:129) |
| sub_x_55       | DW01_dec       | width=9    | sub_129_G48 (SUDOKU.v:129) |
| sub_x_56       | DW01_dec       | width=9    | sub_129_G49 (SUDOKU.v:129) |
| sub_x_57       | DW01_dec       | width=9    | sub_129_G50 (SUDOKU.v:129) |
| sub_x_58       | DW01_dec       | width=9    | sub_129_G51 (SUDOKU.v:129) |
| sub_x_59       | DW01_dec       | width=9    | sub_129_G52 (SUDOKU.v:129) |
| sub_x_60       | DW01_dec       | width=9    | sub_129_G53 (SUDOKU.v:129) |
| sub_x_61       | DW01_dec       | width=9    | sub_129_G54 (SUDOKU.v:129) |
| sub_x_62       | DW01_dec       | width=9    | sub_129_G55 (SUDOKU.v:129) |
| sub_x_63       | DW01_dec       | width=9    | sub_129_G56 (SUDOKU.v:129) |
| sub_x_64       | DW01_dec       | width=9    | sub_129_G57 (SUDOKU.v:129) |
| sub_x_65       | DW01_dec       | width=9    | sub_129_G58 (SUDOKU.v:129) |
| sub_x_66       | DW01_dec       | width=9    | sub_129_G59 (SUDOKU.v:129) |
| sub_x_67       | DW01_dec       | width=9    | sub_129_G60 (SUDOKU.v:129) |
| sub_x_68       | DW01_dec       | width=9    | sub_129_G61 (SUDOKU.v:129) |
| sub_x_69       | DW01_dec       | width=9    | sub_129_G62 (SUDOKU.v:129) |
| sub_x_70       | DW01_dec       | width=9    | sub_129_G63 (SUDOKU.v:129) |
| sub_x_71       | DW01_dec       | width=9    | sub_129_G64 (SUDOKU.v:129) |
| sub_x_72       | DW01_dec       | width=9    | sub_129_G65 (SUDOKU.v:129) |
| sub_x_73       | DW01_dec       | width=9    | sub_129_G66 (SUDOKU.v:129) |
| sub_x_74       | DW01_dec       | width=9    | sub_129_G67 (SUDOKU.v:129) |
| sub_x_75       | DW01_dec       | width=9    | sub_129_G68 (SUDOKU.v:129) |
| sub_x_76       | DW01_dec       | width=9    | sub_129_G69 (SUDOKU.v:129) |
| sub_x_77       | DW01_dec       | width=9    | sub_129_G70 (SUDOKU.v:129) |
| sub_x_78       | DW01_dec       | width=9    | sub_129_G71 (SUDOKU.v:129) |
| sub_x_79       | DW01_dec       | width=9    | sub_129_G72 (SUDOKU.v:129) |
| sub_x_80       | DW01_dec       | width=9    | sub_129_G73 (SUDOKU.v:129) |
| sub_x_81       | DW01_dec       | width=9    | sub_129_G74 (SUDOKU.v:129) |
| sub_x_82       | DW01_dec       | width=9    | sub_129_G75 (SUDOKU.v:129) |
| sub_x_83       | DW01_dec       | width=9    | sub_129_G76 (SUDOKU.v:129) |
| sub_x_84       | DW01_dec       | width=9    | sub_129_G77 (SUDOKU.v:129) |
| sub_x_85       | DW01_dec       | width=9    | sub_129_G78 (SUDOKU.v:129) |
| sub_x_86       | DW01_dec       | width=9    | sub_129_G79 (SUDOKU.v:129) |
| sub_x_87       | DW01_dec       | width=9    | sub_129_G80 (SUDOKU.v:129) |
| sub_x_88       | DW01_dec       | width=9    | sub_129_G81 (SUDOKU.v:129) |
| add_x_1862     | DW01_inc       | width=7    | add_305_S2 (SUDOKU.v:305)  |
| sub_x_170      | DW01_dec       | width=9    | sub_174 (SUDOKU.v:174)     |
|                |                |            | sub_174_G2_G1_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G1_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G1_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G1_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G1_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G1_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G1_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G1_G1 (SUDOKU.v:174) |
| sub_x_189      | DW01_dec       | width=9    | sub_174_G2_G1 (SUDOKU.v:174) |
               |                |            | sub_174_G2_G2_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G2_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G2_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G2_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G2_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G2_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G2_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G2_G1 (SUDOKU.v:174) |
| sub_x_208      | DW01_dec       | width=9    | sub_174_G2_G3_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G1 (SUDOKU.v:174) |
               |                |            | sub_174_G3_G3_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G3_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G3_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G3_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G3_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G3_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G3_G1 (SUDOKU.v:174) |
| sub_x_227      | DW01_dec       | width=9    | sub_174_G2_G4_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G4_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G1 (SUDOKU.v:174) |
               |                |            | sub_174_G4_G4_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G4_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G4_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G4_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G4_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G4_G1 (SUDOKU.v:174) |
| sub_x_246      | DW01_dec       | width=9    | sub_174_G2_G5_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G5_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G5_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G1 (SUDOKU.v:174) |
               |                |            | sub_174_G5_G5_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G5_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G5_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G5_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G5_G1 (SUDOKU.v:174) |
| sub_x_265      | DW01_dec       | width=9    | sub_174_G2_G6_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G6_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G6_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G6_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G1 (SUDOKU.v:174) |
               |                |            | sub_174_G6_G6_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G6_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G6_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G6_G1 (SUDOKU.v:174) |
| sub_x_284      | DW01_dec       | width=9    | sub_174_G2_G7_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G7_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G7_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G7_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G7_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G1 (SUDOKU.v:174) |
               |                |            | sub_174_G7_G7_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G7_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G7_G1 (SUDOKU.v:174) |
| sub_x_303      | DW01_dec       | width=9    | sub_174_G2_G8_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G8_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G8_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G8_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G8_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G8_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G1 (SUDOKU.v:174) |
               |                |            | sub_174_G8_G8_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G8_G1 (SUDOKU.v:174) |
| sub_x_322      | DW01_dec       | width=9    | sub_174_G2_G9_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G9_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G9_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G9_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G9_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G9_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G9_G1 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G1 (SUDOKU.v:174) |
               |                |            | sub_174_G9_G9_G1 (SUDOKU.v:174) |
| sub_x_341      | DW01_dec       | width=9    | sub_174_G2 (SUDOKU.v:174)  |
|                |                |            | sub_174_G2_G1_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G1_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G1_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G1_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G1_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G1_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G1_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G1_G2 (SUDOKU.v:174) |
| sub_x_360      | DW01_dec       | width=9    | sub_174_G2_G2 (SUDOKU.v:174) |
               |                |            | sub_174_G2_G2_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G2_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G2_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G2_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G2_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G2_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G2_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G2_G2 (SUDOKU.v:174) |
| sub_x_379      | DW01_dec       | width=9    | sub_174_G2_G3_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G2 (SUDOKU.v:174) |
               |                |            | sub_174_G3_G3_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G3_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G3_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G3_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G3_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G3_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G3_G2 (SUDOKU.v:174) |
| sub_x_398      | DW01_dec       | width=9    | sub_174_G2_G4_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G4_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G2 (SUDOKU.v:174) |
               |                |            | sub_174_G4_G4_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G4_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G4_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G4_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G4_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G4_G2 (SUDOKU.v:174) |
| sub_x_417      | DW01_dec       | width=9    | sub_174_G2_G5_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G5_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G5_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G2 (SUDOKU.v:174) |
               |                |            | sub_174_G5_G5_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G5_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G5_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G5_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G5_G2 (SUDOKU.v:174) |
| sub_x_436      | DW01_dec       | width=9    | sub_174_G2_G6_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G6_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G6_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G6_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G2 (SUDOKU.v:174) |
               |                |            | sub_174_G6_G6_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G6_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G6_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G6_G2 (SUDOKU.v:174) |
| sub_x_455      | DW01_dec       | width=9    | sub_174_G2_G7_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G7_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G7_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G7_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G7_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G2 (SUDOKU.v:174) |
               |                |            | sub_174_G7_G7_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G7_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G7_G2 (SUDOKU.v:174) |
| sub_x_474      | DW01_dec       | width=9    | sub_174_G2_G8_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G8_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G8_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G8_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G8_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G8_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G2 (SUDOKU.v:174) |
               |                |            | sub_174_G8_G8_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G8_G2 (SUDOKU.v:174) |
| sub_x_493      | DW01_dec       | width=9    | sub_174_G2_G9_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G9_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G9_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G9_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G9_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G9_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G9_G2 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G2 (SUDOKU.v:174) |
               |                |            | sub_174_G9_G9_G2 (SUDOKU.v:174) |
| sub_x_512      | DW01_dec       | width=9    | sub_174_G2_G1_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G3 (SUDOKU.v:174)  |
|                |                |            | sub_174_G3_G1_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G1_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G1_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G1_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G1_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G1_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G1_G3 (SUDOKU.v:174) |
| sub_x_531      | DW01_dec       | width=9    | sub_174_G2_G2_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G2_G3 (SUDOKU.v:174) |
               |                |            | sub_174_G3_G2_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G2_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G2_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G2_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G2_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G2_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G2_G3 (SUDOKU.v:174) |
| sub_x_550      | DW01_dec       | width=9    | sub_174_G2_G3_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G3 (SUDOKU.v:174) |
               |                |            | sub_174_G3_G3_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G3_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G3_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G3_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G3_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G3_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G3_G3 (SUDOKU.v:174) |
| sub_x_569      | DW01_dec       | width=9    | sub_174_G2_G4_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G4_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G3 (SUDOKU.v:174) |
               |                |            | sub_174_G4_G4_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G4_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G4_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G4_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G4_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G4_G3 (SUDOKU.v:174) |
| sub_x_588      | DW01_dec       | width=9    | sub_174_G2_G5_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G5_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G5_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G3 (SUDOKU.v:174) |
               |                |            | sub_174_G5_G5_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G5_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G5_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G5_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G5_G3 (SUDOKU.v:174) |
| sub_x_607      | DW01_dec       | width=9    | sub_174_G2_G6_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G6_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G6_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G6_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G3 (SUDOKU.v:174) |
               |                |            | sub_174_G6_G6_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G6_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G6_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G6_G3 (SUDOKU.v:174) |
| sub_x_626      | DW01_dec       | width=9    | sub_174_G2_G7_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G7_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G7_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G7_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G7_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G3 (SUDOKU.v:174) |
               |                |            | sub_174_G7_G7_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G7_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G7_G3 (SUDOKU.v:174) |
| sub_x_645      | DW01_dec       | width=9    | sub_174_G2_G8_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G8_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G8_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G8_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G8_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G8_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G3 (SUDOKU.v:174) |
               |                |            | sub_174_G8_G8_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G8_G3 (SUDOKU.v:174) |
| sub_x_664      | DW01_dec       | width=9    | sub_174_G2_G9_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G9_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G9_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G9_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G9_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G9_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G9_G3 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G3 (SUDOKU.v:174) |
               |                |            | sub_174_G9_G9_G3 (SUDOKU.v:174) |
| sub_x_683      | DW01_dec       | width=9    | sub_174_G2_G1_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G1_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G4 (SUDOKU.v:174)  |
|                |                |            | sub_174_G4_G1_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G1_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G1_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G1_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G1_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G1_G4 (SUDOKU.v:174) |
| sub_x_702      | DW01_dec       | width=9    | sub_174_G2_G2_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G2_G4 (SUDOKU.v:174) |
               |                |            | sub_174_G3_G2_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G2_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G2_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G2_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G2_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G2_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G2_G4 (SUDOKU.v:174) |
| sub_x_721      | DW01_dec       | width=9    | sub_174_G2_G3_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G3_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G4 (SUDOKU.v:174) |
               |                |            | sub_174_G4_G3_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G3_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G3_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G3_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G3_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G3_G4 (SUDOKU.v:174) |
| sub_x_740      | DW01_dec       | width=9    | sub_174_G2_G4_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G4_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G4 (SUDOKU.v:174) |
               |                |            | sub_174_G4_G4_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G4_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G4_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G4_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G4_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G4_G4 (SUDOKU.v:174) |
| sub_x_759      | DW01_dec       | width=9    | sub_174_G2_G5_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G5_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G5_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G4 (SUDOKU.v:174) |
               |                |            | sub_174_G5_G5_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G5_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G5_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G5_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G5_G4 (SUDOKU.v:174) |
| sub_x_778      | DW01_dec       | width=9    | sub_174_G2_G6_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G6_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G6_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G6_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G4 (SUDOKU.v:174) |
               |                |            | sub_174_G6_G6_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G6_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G6_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G6_G4 (SUDOKU.v:174) |
| sub_x_797      | DW01_dec       | width=9    | sub_174_G2_G7_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G7_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G7_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G7_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G7_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G4 (SUDOKU.v:174) |
               |                |            | sub_174_G7_G7_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G7_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G7_G4 (SUDOKU.v:174) |
| sub_x_816      | DW01_dec       | width=9    | sub_174_G2_G8_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G8_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G8_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G8_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G8_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G8_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G4 (SUDOKU.v:174) |
               |                |            | sub_174_G8_G8_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G8_G4 (SUDOKU.v:174) |
| sub_x_835      | DW01_dec       | width=9    | sub_174_G2_G9_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G9_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G9_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G9_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G9_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G9_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G9_G4 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G4 (SUDOKU.v:174) |
               |                |            | sub_174_G9_G9_G4 (SUDOKU.v:174) |
| sub_x_854      | DW01_dec       | width=9    | sub_174_G2_G1_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G1_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G1_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G5 (SUDOKU.v:174)  |
|                |                |            | sub_174_G5_G1_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G1_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G1_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G1_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G1_G5 (SUDOKU.v:174) |
| sub_x_873      | DW01_dec       | width=9    | sub_174_G2_G2_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G2_G5 (SUDOKU.v:174) |
               |                |            | sub_174_G3_G2_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G2_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G2_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G2_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G2_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G2_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G2_G5 (SUDOKU.v:174) |
| sub_x_892      | DW01_dec       | width=9    | sub_174_G2_G3_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G3_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G5 (SUDOKU.v:174) |
               |                |            | sub_174_G4_G3_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G3_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G3_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G3_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G3_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G3_G5 (SUDOKU.v:174) |
| sub_x_911      | DW01_dec       | width=9    | sub_174_G2_G4_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G4_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G4_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G5 (SUDOKU.v:174) |
               |                |            | sub_174_G5_G4_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G4_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G4_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G4_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G4_G5 (SUDOKU.v:174) |
| sub_x_930      | DW01_dec       | width=9    | sub_174_G2_G5_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G5_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G5_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G5 (SUDOKU.v:174) |
               |                |            | sub_174_G5_G5_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G5_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G5_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G5_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G5_G5 (SUDOKU.v:174) |
| sub_x_949      | DW01_dec       | width=9    | sub_174_G2_G6_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G6_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G6_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G6_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G5 (SUDOKU.v:174) |
               |                |            | sub_174_G6_G6_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G6_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G6_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G6_G5 (SUDOKU.v:174) |
| sub_x_968      | DW01_dec       | width=9    | sub_174_G2_G7_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G7_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G7_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G7_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G7_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G5 (SUDOKU.v:174) |
               |                |            | sub_174_G7_G7_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G7_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G7_G5 (SUDOKU.v:174) |
| sub_x_987      | DW01_dec       | width=9    | sub_174_G2_G8_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G8_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G8_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G8_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G8_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G8_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G5 (SUDOKU.v:174) |
               |                |            | sub_174_G8_G8_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G8_G5 (SUDOKU.v:174) |
| sub_x_1006     | DW01_dec       | width=9    | sub_174_G2_G9_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G9_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G9_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G9_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G9_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G9_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G9_G5 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G5 (SUDOKU.v:174) |
               |                |            | sub_174_G9_G9_G5 (SUDOKU.v:174) |
| sub_x_1025     | DW01_dec       | width=9    | sub_174_G2_G1_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G1_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G1_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G1_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G6 (SUDOKU.v:174)  |
|                |                |            | sub_174_G6_G1_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G1_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G1_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G1_G6 (SUDOKU.v:174) |
| sub_x_1044     | DW01_dec       | width=9    | sub_174_G2_G2_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G2_G6 (SUDOKU.v:174) |
               |                |            | sub_174_G3_G2_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G2_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G2_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G2_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G2_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G2_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G2_G6 (SUDOKU.v:174) |
| sub_x_1063     | DW01_dec       | width=9    | sub_174_G2_G3_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G3_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G6 (SUDOKU.v:174) |
               |                |            | sub_174_G4_G3_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G3_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G3_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G3_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G3_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G3_G6 (SUDOKU.v:174) |
| sub_x_1082     | DW01_dec       | width=9    | sub_174_G2_G4_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G4_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G4_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G6 (SUDOKU.v:174) |
               |                |            | sub_174_G5_G4_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G4_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G4_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G4_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G4_G6 (SUDOKU.v:174) |
| sub_x_1101     | DW01_dec       | width=9    | sub_174_G2_G5_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G5_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G5_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G5_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G6 (SUDOKU.v:174) |
               |                |            | sub_174_G6_G5_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G5_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G5_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G5_G6 (SUDOKU.v:174) |
| sub_x_1120     | DW01_dec       | width=9    | sub_174_G2_G6_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G6_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G6_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G6_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G6 (SUDOKU.v:174) |
               |                |            | sub_174_G6_G6_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G6_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G6_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G6_G6 (SUDOKU.v:174) |
| sub_x_1139     | DW01_dec       | width=9    | sub_174_G2_G7_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G7_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G7_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G7_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G7_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G6 (SUDOKU.v:174) |
               |                |            | sub_174_G7_G7_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G7_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G7_G6 (SUDOKU.v:174) |
| sub_x_1158     | DW01_dec       | width=9    | sub_174_G2_G8_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G8_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G8_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G8_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G8_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G8_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G6 (SUDOKU.v:174) |
               |                |            | sub_174_G8_G8_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G8_G6 (SUDOKU.v:174) |
| sub_x_1177     | DW01_dec       | width=9    | sub_174_G2_G9_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G9_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G9_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G9_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G9_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G9_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G9_G6 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G6 (SUDOKU.v:174) |
               |                |            | sub_174_G9_G9_G6 (SUDOKU.v:174) |
| sub_x_1196     | DW01_dec       | width=9    | sub_174_G2_G1_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G1_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G1_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G1_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G1_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G7 (SUDOKU.v:174)  |
|                |                |            | sub_174_G7_G1_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G1_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G1_G7 (SUDOKU.v:174) |
| sub_x_1215     | DW01_dec       | width=9    | sub_174_G2_G2_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G2_G7 (SUDOKU.v:174) |
               |                |            | sub_174_G3_G2_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G2_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G2_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G2_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G2_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G2_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G2_G7 (SUDOKU.v:174) |
| sub_x_1234     | DW01_dec       | width=9    | sub_174_G2_G3_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G3_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G7 (SUDOKU.v:174) |
               |                |            | sub_174_G4_G3_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G3_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G3_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G3_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G3_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G3_G7 (SUDOKU.v:174) |
| sub_x_1253     | DW01_dec       | width=9    | sub_174_G2_G4_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G4_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G4_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G7 (SUDOKU.v:174) |
               |                |            | sub_174_G5_G4_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G4_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G4_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G4_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G4_G7 (SUDOKU.v:174) |
| sub_x_1272     | DW01_dec       | width=9    | sub_174_G2_G5_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G5_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G5_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G5_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G7 (SUDOKU.v:174) |
               |                |            | sub_174_G6_G5_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G5_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G5_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G5_G7 (SUDOKU.v:174) |
| sub_x_1291     | DW01_dec       | width=9    | sub_174_G2_G6_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G6_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G6_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G6_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G6_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G7 (SUDOKU.v:174) |
               |                |            | sub_174_G7_G6_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G6_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G6_G7 (SUDOKU.v:174) |
| sub_x_1310     | DW01_dec       | width=9    | sub_174_G2_G7_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G7_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G7_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G7_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G7_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G7 (SUDOKU.v:174) |
               |                |            | sub_174_G7_G7_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G7_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G7_G7 (SUDOKU.v:174) |
| sub_x_1329     | DW01_dec       | width=9    | sub_174_G2_G8_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G8_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G8_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G8_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G8_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G8_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G7 (SUDOKU.v:174) |
               |                |            | sub_174_G8_G8_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G8_G7 (SUDOKU.v:174) |
| sub_x_1348     | DW01_dec       | width=9    | sub_174_G2_G9_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G9_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G9_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G9_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G9_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G9_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G9_G7 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G7 (SUDOKU.v:174) |
               |                |            | sub_174_G9_G9_G7 (SUDOKU.v:174) |
| sub_x_1367     | DW01_dec       | width=9    | sub_174_G2_G1_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G1_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G1_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G1_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G1_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G1_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G8 (SUDOKU.v:174)  |
|                |                |            | sub_174_G8_G1_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G1_G8 (SUDOKU.v:174) |
| sub_x_1386     | DW01_dec       | width=9    | sub_174_G2_G2_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G2_G8 (SUDOKU.v:174) |
               |                |            | sub_174_G3_G2_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G2_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G2_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G2_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G2_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G2_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G2_G8 (SUDOKU.v:174) |
| sub_x_1405     | DW01_dec       | width=9    | sub_174_G2_G3_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G3_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G8 (SUDOKU.v:174) |
               |                |            | sub_174_G4_G3_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G3_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G3_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G3_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G3_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G3_G8 (SUDOKU.v:174) |
| sub_x_1424     | DW01_dec       | width=9    | sub_174_G2_G4_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G4_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G4_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G8 (SUDOKU.v:174) |
               |                |            | sub_174_G5_G4_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G4_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G4_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G4_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G4_G8 (SUDOKU.v:174) |
| sub_x_1443     | DW01_dec       | width=9    | sub_174_G2_G5_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G5_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G5_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G5_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G8 (SUDOKU.v:174) |
               |                |            | sub_174_G6_G5_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G5_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G5_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G5_G8 (SUDOKU.v:174) |
| sub_x_1462     | DW01_dec       | width=9    | sub_174_G2_G6_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G6_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G6_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G6_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G6_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G8 (SUDOKU.v:174) |
               |                |            | sub_174_G7_G6_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G6_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G6_G8 (SUDOKU.v:174) |
| sub_x_1481     | DW01_dec       | width=9    | sub_174_G2_G7_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G7_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G7_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G7_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G7_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G7_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G8 (SUDOKU.v:174) |
               |                |            | sub_174_G8_G7_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G7_G8 (SUDOKU.v:174) |
| sub_x_1500     | DW01_dec       | width=9    | sub_174_G2_G8_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G8_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G8_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G8_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G8_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G8_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G8 (SUDOKU.v:174) |
               |                |            | sub_174_G8_G8_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G8_G8 (SUDOKU.v:174) |
| sub_x_1519     | DW01_dec       | width=9    | sub_174_G2_G9_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G9_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G9_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G9_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G9_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G9_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G9_G8 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G8 (SUDOKU.v:174) |
               |                |            | sub_174_G9_G9_G8 (SUDOKU.v:174) |
| sub_x_1538     | DW01_dec       | width=9    | sub_174_G2_G1_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G1_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G1_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G1_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G1_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G1_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G1_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G9 (SUDOKU.v:174)  |
|                |                |            | sub_174_G9_G1_G9 (SUDOKU.v:174) |
| sub_x_1557     | DW01_dec       | width=9    | sub_174_G2_G2_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G2_G9 (SUDOKU.v:174) |
               |                |            | sub_174_G3_G2_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G2_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G2_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G2_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G2_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G2_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G2_G9 (SUDOKU.v:174) |
| sub_x_1576     | DW01_dec       | width=9    | sub_174_G2_G3_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G3_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G9 (SUDOKU.v:174) |
               |                |            | sub_174_G4_G3_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G3_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G3_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G3_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G3_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G3_G9 (SUDOKU.v:174) |
| sub_x_1595     | DW01_dec       | width=9    | sub_174_G2_G4_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G4_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G4_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G9 (SUDOKU.v:174) |
               |                |            | sub_174_G5_G4_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G4_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G4_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G4_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G4_G9 (SUDOKU.v:174) |
| sub_x_1614     | DW01_dec       | width=9    | sub_174_G2_G5_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G5_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G5_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G5_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G9 (SUDOKU.v:174) |
               |                |            | sub_174_G6_G5_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G5_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G5_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G5_G9 (SUDOKU.v:174) |
| sub_x_1633     | DW01_dec       | width=9    | sub_174_G2_G6_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G6_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G6_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G6_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G6_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G9 (SUDOKU.v:174) |
               |                |            | sub_174_G7_G6_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G6_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G6_G9 (SUDOKU.v:174) |
| sub_x_1652     | DW01_dec       | width=9    | sub_174_G2_G7_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G7_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G7_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G7_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G7_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G7_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G9 (SUDOKU.v:174) |
               |                |            | sub_174_G8_G7_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G7_G9 (SUDOKU.v:174) |
| sub_x_1671     | DW01_dec       | width=9    | sub_174_G2_G8_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G8_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G8_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G8_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G8_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G8_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G8_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G9 (SUDOKU.v:174) |
               |                |            | sub_174_G9_G8_G9 (SUDOKU.v:174) |
| sub_x_1690     | DW01_dec       | width=9    | sub_174_G2_G9_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G3_G9_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G4_G9_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G5_G9_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G6_G9_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G7_G9_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G8_G9_G9 (SUDOKU.v:174) |
            |                |            | sub_174_G9_G9 (SUDOKU.v:174) |
               |                |            | sub_174_G9_G9_G9 (SUDOKU.v:174) |
=============================================================================


Resource Report for Ungrouped Hierarchy rem_4
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
=============================================================================


Resource Report for Ungrouped Hierarchy div_3
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
=============================================================================


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| gt_x_1             | DW_cmp           | apparch (area)     |                |
| div_3              | DW_div_uns       | cla                |                |
| rem_4              | DW_div_uns       | cla                |                |
| add_x_6            | DW01_inc         | apparch (area)     |                |
| sub_x_8            | DW01_dec         | apparch (area)     |                |
| sub_x_9            | DW01_dec         | apparch (area)     |                |
| sub_x_10           | DW01_dec         | apparch (area)     |                |
| sub_x_11           | DW01_dec         | apparch (area)     |                |
| sub_x_12           | DW01_dec         | apparch (area)     |                |
| sub_x_13           | DW01_dec         | apparch (area)     |                |
| sub_x_14           | DW01_dec         | apparch (area)     |                |
| sub_x_15           | DW01_dec         | apparch (area)     |                |
| sub_x_16           | DW01_dec         | apparch (area)     |                |
| sub_x_17           | DW01_dec         | apparch (area)     |                |
| sub_x_18           | DW01_dec         | apparch (area)     |                |
| sub_x_19           | DW01_dec         | apparch (area)     |                |
| sub_x_20           | DW01_dec         | apparch (area)     |                |
| sub_x_21           | DW01_dec         | apparch (area)     |                |
| sub_x_22           | DW01_dec         | apparch (area)     |                |
| sub_x_23           | DW01_dec         | apparch (area)     |                |
| sub_x_24           | DW01_dec         | apparch (area)     |                |
| sub_x_25           | DW01_dec         | apparch (area)     |                |
| sub_x_26           | DW01_dec         | apparch (area)     |                |
| sub_x_27           | DW01_dec         | apparch (area)     |                |
| sub_x_28           | DW01_dec         | apparch (area)     |                |
| sub_x_29           | DW01_dec         | apparch (area)     |                |
| sub_x_30           | DW01_dec         | apparch (area)     |                |
| sub_x_31           | DW01_dec         | apparch (area)     |                |
| sub_x_32           | DW01_dec         | apparch (area)     |                |
| sub_x_33           | DW01_dec         | apparch (area)     |                |
| sub_x_34           | DW01_dec         | apparch (area)     |                |
| sub_x_35           | DW01_dec         | apparch (area)     |                |
| sub_x_36           | DW01_dec         | apparch (area)     |                |
| sub_x_37           | DW01_dec         | apparch (area)     |                |
| sub_x_38           | DW01_dec         | apparch (area)     |                |
| sub_x_39           | DW01_dec         | apparch (area)     |                |
| sub_x_40           | DW01_dec         | apparch (area)     |                |
| sub_x_41           | DW01_dec         | apparch (area)     |                |
| sub_x_42           | DW01_dec         | apparch (area)     |                |
| sub_x_43           | DW01_dec         | apparch (area)     |                |
| sub_x_44           | DW01_dec         | apparch (area)     |                |
| sub_x_45           | DW01_dec         | apparch (area)     |                |
| sub_x_46           | DW01_dec         | apparch (area)     |                |
| sub_x_47           | DW01_dec         | apparch (area)     |                |
| sub_x_48           | DW01_dec         | apparch (area)     |                |
| sub_x_49           | DW01_dec         | apparch (area)     |                |
| sub_x_50           | DW01_dec         | apparch (area)     |                |
| sub_x_51           | DW01_dec         | apparch (area)     |                |
| sub_x_52           | DW01_dec         | apparch (area)     |                |
| sub_x_53           | DW01_dec         | apparch (area)     |                |
| sub_x_54           | DW01_dec         | apparch (area)     |                |
| sub_x_55           | DW01_dec         | apparch (area)     |                |
| sub_x_56           | DW01_dec         | apparch (area)     |                |
| sub_x_57           | DW01_dec         | apparch (area)     |                |
| sub_x_58           | DW01_dec         | apparch (area)     |                |
| sub_x_59           | DW01_dec         | apparch (area)     |                |
| sub_x_60           | DW01_dec         | apparch (area)     |                |
| sub_x_61           | DW01_dec         | apparch (area)     |                |
| sub_x_62           | DW01_dec         | apparch (area)     |                |
| sub_x_63           | DW01_dec         | apparch (area)     |                |
| sub_x_64           | DW01_dec         | apparch (area)     |                |
| sub_x_65           | DW01_dec         | apparch (area)     |                |
| sub_x_66           | DW01_dec         | apparch (area)     |                |
| sub_x_67           | DW01_dec         | apparch (area)     |                |
| sub_x_68           | DW01_dec         | apparch (area)     |                |
| sub_x_69           | DW01_dec         | apparch (area)     |                |
| sub_x_70           | DW01_dec         | apparch (area)     |                |
| sub_x_71           | DW01_dec         | apparch (area)     |                |
| sub_x_72           | DW01_dec         | apparch (area)     |                |
| sub_x_73           | DW01_dec         | apparch (area)     |                |
| sub_x_74           | DW01_dec         | apparch (area)     |                |
| sub_x_75           | DW01_dec         | apparch (area)     |                |
| sub_x_76           | DW01_dec         | apparch (area)     |                |
| sub_x_77           | DW01_dec         | apparch (area)     |                |
| sub_x_78           | DW01_dec         | apparch (area)     |                |
| sub_x_79           | DW01_dec         | apparch (area)     |                |
| sub_x_80           | DW01_dec         | apparch (area)     |                |
| sub_x_81           | DW01_dec         | apparch (area)     |                |
| sub_x_82           | DW01_dec         | apparch (area)     |                |
| sub_x_83           | DW01_dec         | apparch (area)     |                |
| sub_x_84           | DW01_dec         | apparch (area)     |                |
| sub_x_85           | DW01_dec         | apparch (area)     |                |
| sub_x_86           | DW01_dec         | apparch (area)     |                |
| sub_x_87           | DW01_dec         | apparch (area)     |                |
| sub_x_88           | DW01_dec         | apparch (area)     |                |
| add_x_1862         | DW01_inc         | apparch (area)     |                |
| sub_x_170          | DW01_dec         | apparch (area)     |                |
| sub_x_189          | DW01_dec         | apparch (area)     |                |
| sub_x_208          | DW01_dec         | apparch (area)     |                |
| sub_x_227          | DW01_dec         | apparch (area)     |                |
| sub_x_246          | DW01_dec         | apparch (area)     |                |
| sub_x_265          | DW01_dec         | apparch (area)     |                |
| sub_x_284          | DW01_dec         | apparch (area)     |                |
| sub_x_303          | DW01_dec         | apparch (area)     |                |
| sub_x_322          | DW01_dec         | apparch (area)     |                |
| sub_x_341          | DW01_dec         | apparch (area)     |                |
| sub_x_360          | DW01_dec         | apparch (area)     |                |
| sub_x_379          | DW01_dec         | apparch (area)     |                |
| sub_x_398          | DW01_dec         | apparch (area)     |                |
| sub_x_417          | DW01_dec         | apparch (area)     |                |
| sub_x_436          | DW01_dec         | apparch (area)     |                |
| sub_x_455          | DW01_dec         | apparch (area)     |                |
| sub_x_474          | DW01_dec         | apparch (area)     |                |
| sub_x_493          | DW01_dec         | apparch (area)     |                |
| sub_x_512          | DW01_dec         | apparch (area)     |                |
| sub_x_531          | DW01_dec         | apparch (area)     |                |
| sub_x_550          | DW01_dec         | apparch (area)     |                |
| sub_x_569          | DW01_dec         | apparch (area)     |                |
| sub_x_588          | DW01_dec         | apparch (area)     |                |
| sub_x_607          | DW01_dec         | apparch (area)     |                |
| sub_x_626          | DW01_dec         | apparch (area)     |                |
| sub_x_645          | DW01_dec         | apparch (area)     |                |
| sub_x_664          | DW01_dec         | apparch (area)     |                |
| sub_x_683          | DW01_dec         | apparch (area)     |                |
| sub_x_702          | DW01_dec         | apparch (area)     |                |
| sub_x_721          | DW01_dec         | apparch (area)     |                |
| sub_x_740          | DW01_dec         | apparch (area)     |                |
| sub_x_759          | DW01_dec         | apparch (area)     |                |
| sub_x_778          | DW01_dec         | apparch (area)     |                |
| sub_x_797          | DW01_dec         | apparch (area)     |                |
| sub_x_816          | DW01_dec         | apparch (area)     |                |
| sub_x_835          | DW01_dec         | apparch (area)     |                |
| sub_x_854          | DW01_dec         | apparch (area)     |                |
| sub_x_873          | DW01_dec         | apparch (area)     |                |
| sub_x_892          | DW01_dec         | apparch (area)     |                |
| sub_x_911          | DW01_dec         | apparch (area)     |                |
| sub_x_930          | DW01_dec         | apparch (area)     |                |
| sub_x_949          | DW01_dec         | apparch (area)     |                |
| sub_x_968          | DW01_dec         | apparch (area)     |                |
| sub_x_987          | DW01_dec         | apparch (area)     |                |
| sub_x_1006         | DW01_dec         | apparch (area)     |                |
| sub_x_1025         | DW01_dec         | apparch (area)     |                |
| sub_x_1044         | DW01_dec         | apparch (area)     |                |
| sub_x_1063         | DW01_dec         | apparch (area)     |                |
| sub_x_1082         | DW01_dec         | apparch (area)     |                |
| sub_x_1101         | DW01_dec         | apparch (area)     |                |
| sub_x_1120         | DW01_dec         | apparch (area)     |                |
| sub_x_1139         | DW01_dec         | apparch (area)     |                |
| sub_x_1158         | DW01_dec         | apparch (area)     |                |
| sub_x_1177         | DW01_dec         | apparch (area)     |                |
| sub_x_1196         | DW01_dec         | apparch (area)     |                |
| sub_x_1215         | DW01_dec         | apparch (area)     |                |
| sub_x_1234         | DW01_dec         | apparch (area)     |                |
| sub_x_1253         | DW01_dec         | apparch (area)     |                |
| sub_x_1272         | DW01_dec         | apparch (area)     |                |
| sub_x_1291         | DW01_dec         | apparch (area)     |                |
| sub_x_1310         | DW01_dec         | apparch (area)     |                |
| sub_x_1329         | DW01_dec         | apparch (area)     |                |
| sub_x_1348         | DW01_dec         | apparch (area)     |                |
| sub_x_1367         | DW01_dec         | apparch (area)     |                |
| sub_x_1386         | DW01_dec         | apparch (area)     |                |
| sub_x_1405         | DW01_dec         | apparch (area)     |                |
| sub_x_1424         | DW01_dec         | apparch (area)     |                |
| sub_x_1443         | DW01_dec         | apparch (area)     |                |
| sub_x_1462         | DW01_dec         | apparch (area)     |                |
| sub_x_1481         | DW01_dec         | apparch (area)     |                |
| sub_x_1500         | DW01_dec         | apparch (area)     |                |
| sub_x_1519         | DW01_dec         | apparch (area)     |                |
| sub_x_1538         | DW01_dec         | apparch (area)     |                |
| sub_x_1557         | DW01_dec         | apparch (area)     |                |
| sub_x_1576         | DW01_dec         | apparch (area)     |                |
| sub_x_1595         | DW01_dec         | apparch (area)     |                |
| sub_x_1614         | DW01_dec         | apparch (area)     |                |
| sub_x_1633         | DW01_dec         | apparch (area)     |                |
| sub_x_1652         | DW01_dec         | apparch (area)     |                |
| sub_x_1671         | DW01_dec         | apparch (area)     |                |
| sub_x_1690         | DW01_dec         | apparch (area)     |                |
===============================================================================

1
